### ISSUE TITLE
Cluster is unusable during scale operation

### ISSUE THREAD

**Issue by vmeln** [k8ssandra/k8ssandra#1045]
**What did you do?**
Connected from JanusGraph hosted in AKS, to Cassandra datacenter hosted in AKS. Tried to connect directly to the datacenter with _all-pods-service_ or  through the Stargate CQL API and the result is the same - client app can't reach Cassandra nodes during the scale (up and down) and goes offline for a minute or two with the following error:
<details>
<summary>Stack Trace</summary>

```
11:27:18 WARN  org.janusgraph.diskstorage.log.kcvs.KCVSLog  - Could not read messages for timestamp [2021-08-18T11:26:03.192Z] (this read will be retried)
org.janusgraph.core.JanusGraphException: Could not execute operation due to backend exception
        at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:56)
        at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:158)
        at org.janusgraph.diskstorage.log.kcvs.KCVSLog$MessagePuller.run(KCVSLog.java:725)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.janusgraph.diskstorage.TemporaryBackendException: Could not successfully complete backend operation due to repeated temporary exceptions after PT4S
        at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:100)
        at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:54)
        ... 9 more
Caused by: org.janusgraph.diskstorage.TemporaryBackendException: Temporary failure in storage backend
        at io.vavr.API$Match$Case0.apply(API.java:3174)
        at io.vavr.API$Match.of(API.java:3137)
        at org.janusgraph.diskstorage.cql.CQLKeyColumnValueStore.lambda$static$0(CQLKeyColumnValueStore.java:123)
        at io.vavr.control.Try.getOrElseThrow(Try.java:671)
        at org.janusgraph.diskstorage.cql.CQLKeyColumnValueStore.getSlice(CQLKeyColumnValueStore.java:290)
        at org.janusgraph.diskstorage.log.kcvs.KCVSLog$MessagePuller$1.call(KCVSLog.java:791)
        at org.janusgraph.diskstorage.log.kcvs.KCVSLog$MessagePuller$1.call(KCVSLog.java:788)
        at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:147)
        at org.janusgraph.diskstorage.util.BackendOperation$1.call(BackendOperation.java:161)
        at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:68)
        ... 10 more
Caused by: java.util.concurrent.ExecutionException: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /10.244.2.46:9042 (com.datastax.driver.core.exceptions.UnavailableExcept
ion: Not enough replicas available for query at consistency QUORUM (1 required but only 0 alive)))
        at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
        at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
        at io.vavr.control.Try.of(Try.java:62)
        at io.vavr.concurrent.FutureImpl.lambda$run$2(FutureImpl.java:199)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        ... 3 more
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /10.244.2.46:9042 (com.datastax.driver.core.exceptions.UnavailableException: Not enough replicas available for qu
ery at consistency QUORUM (1 required but only 0 alive)))
        at com.datastax.driver.core.RequestHandler.reportNoMoreHosts(RequestHandler.java:283)
        at com.datastax.driver.core.RequestHandler.access$1200(RequestHandler.java:61)
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.findNextHostAndQuery(RequestHandler.java:375)
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.retry(RequestHandler.java:563)
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.processRetryDecision(RequestHandler.java:545)
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:816)
        at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1262)
        at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1180)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
        at com.datastax.driver.core.InboundTrafficMeter.channelRead(InboundTrafficMeter.java:38)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        ... 1 more
```
</details>

Is it expected behavior and scale or pod scheduling should be planned beforehand or I'm doing something completely wrong?

**Did you expect to see some different?**
I expected that client apps can still connect to the cluster and operate during Cassandra cluster scale. 

**Environment**
Azure Kubernetes Services

**Helm charts version**
1.3.0

**Comment by jdonenine** [comment]
Hi @vmeln can you tell us a bit about the K8ssandra deployment itself?  If you could drop the helm values used to deploy the cluster and a describe of CassandraDatacenter resources in the cluster that would help as well.

**Comment by vmeln** [comment]
@jdonenine Sure, values file for the chart, it's slightly modified quickstart guide:
```yaml
cassandra:
  version: "3.11.10"
  cassandraLibDirVolume:
    storageClass: azurefile
    size: 5Gi
  allowMultipleNodesPerWorker: true
  heap:
   size: 1G
   newGenSize: 1G
  resources:
    requests:
      cpu: 2000m
      memory: 2Gi
    limits:
      cpu: 3000m
      memory: 2Gi
  datacenters:
  - name: dc1
    size: 3
    racks:
    - name: default
kube-prometheus-stack:
  grafana:
    adminUser: admin
    adminPassword: strongpassword
stargate:
  enabled: true
  replicas: 1
  heapMB: 256
  cpuReqMillicores: 200
  cpuLimMillicores: 1000
```
I have the only issue when changing the _cassandra.datacenters[0].size_ property, everything else runs smoothly.

**Comment by jsanda** [comment]
Hey @vmeln 

In general you should use the datacenter service to access the cluster, not the all-pods service. The all-pods service will include endpoints for pods that are not yet ready. The datacenter service will only include endpoints for pods that are ready. I don't know if that is the issue here though. Is the client eventually able to make a connection?

**Comment by vmeln** [comment]
hi @jsanda, thanks for this suggestion. But, the behavior is still the same with _dc1-service_. However, when I connected and tried to query the table via _cqlsh_ I received this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/cqlsh", line 1076, in perform_simple_statement
    result = future.result()
  File "cassandra/cluster.py", line 4894, in cassandra.cluster.ResponseFuture.result
cassandra.Unavailable: Error from server: code=1000 [Unavailable exception] message="Cannot achieve consistency level ONE" info={'consistency': 'ONE', 'required_replicas': 1, 'alive_replicas': 0}
```
Does it mean that the replication factor conditions are not met and the keyspace is unusable till the node returns to cluster? I'm just confused with _alive_replicas: 0_ in a four-node cluster.

**Comment by jsanda** [comment]
I am going to assume that the keyspace has a replication_factor or 1 which means there is one copy of the data. To be more precise there is 1 copy or replica of each partition. Different partitions will be owned different Cassandra nodes, but there will only be 1 copy of each partition in the cluster. 

The error message is saying that the node owns who owns the partition is unavailable. Another query for a different partition might succeed. 

It would be good to verify the replication settings by running the `describe keyspace <keyspace-name>` in cqlsh.

Are all of the Cassandra pods in the ready state? 

Lastly, you can check Cassandra logs with `kubectl logs <cassandra-pod> -c server-system-logger`.
