### ISSUE TITLE
Stargate shows InstanceAlreadyExistsException after upgrading helm

### ISSUE THREAD

**Issue by royrijkers** [k8ssandra/k8ssandra#1085]
## Bug Report

**Describe the bug**
Stargate shows InstanceAlreadyExistsException after upgrading helm

**To Reproduce**
1. Deploy cluster like in the getting started guide
2. Then upgrade the cluster by assigning more memory for example
3. Now stargate used to crash for me

**Expected behavior**
Stargate does still work after upgrade

**Error**
```
ERROR [StorageServiceShutdownHook] 2021-09-06 08:55:06,874 StorageService.java:4942 - Caught an exception while draining 
java.lang.RuntimeException: javax.management.InstanceAlreadyExistsException: org.apache.cassandra.db:type=IndexTables,keyspace=projects_08753e97_e449_4c94_965a_aefbeb5a3af4,table=access.access_customer_id
	at org.apache.cassandra.utils.MBeanWrapper$OnException.lambda$static$0(MBeanWrapper.java:175)
	at org.apache.cassandra.utils.MBeanWrapper$PlatformMBeanWrapper.registerMBean(MBeanWrapper.java:143)
	at org.apache.cassandra.utils.MBeanWrapper.registerMBean(MBeanWrapper.java:66)
	at org.apache.cassandra.utils.MBeanWrapper.registerMBean(MBeanWrapper.java:70)
	at org.apache.cassandra.db.ColumnFamilyStore.<init>(ColumnFamilyStore.java:447)
	at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:623)
	at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:597)
	at org.apache.cassandra.index.internal.CassandraIndex.setMetadata(CassandraIndex.java:227)
	at org.apache.cassandra.index.internal.CassandraIndex.<init>(CassandraIndex.java:84)
	at org.apache.cassandra.index.internal.composites.RegularColumnIndex.<init>(RegularColumnIndex.java:53)
	at org.apache.cassandra.index.internal.CassandraIndexFunctions$2.newIndexInstance(CassandraIndexFunctions.java:108)
	at org.apache.cassandra.index.internal.CassandraIndex.newIndex(CassandraIndex.java:762)
	at org.apache.cassandra.index.SecondaryIndexManager.createInstance(SecondaryIndexManager.java:773)
	at org.apache.cassandra.index.SecondaryIndexManager.createIndex(SecondaryIndexManager.java:215)
	at org.apache.cassandra.index.SecondaryIndexManager.addIndex(SecondaryIndexManager.java:278)
	at org.apache.cassandra.db.ColumnFamilyStore.<init>(ColumnFamilyStore.java:429)
	at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:623)
	at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:597)
	at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:588)
	at org.apache.cassandra.db.Keyspace.initCf(Keyspace.java:461)
	at org.apache.cassandra.db.Keyspace.<init>(Keyspace.java:355)
	at org.apache.cassandra.db.Keyspace.open(Keyspace.java:148)
	at org.apache.cassandra.db.Keyspace.open(Keyspace.java:124)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:785)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at org.apache.cassandra.service.StorageService.drain(StorageService.java:4871)
	at org.apache.cassandra.service.StorageService$1.runMayThrow(StorageService.java:759)
	at org.apache.cassandra.utils.WrappedRunnable.run(WrappedRunnable.java:28)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.management.InstanceAlreadyExistsException: org.apache.cassandra.db:type=IndexTables,keyspace=projects_08753e97_e449_4c94_965a_aefbeb5a3af4,table=access.access_customer_id
	at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
	at org.apache.cassandra.utils.MBeanWrapper$PlatformMBeanWrapper.registerMBean(MBeanWrapper.java:139)
	... 28 common frames omitted
```
**Environment (please complete the following information):**

* Helm charts version info

`k8ssandra   	default  	5       	2021-08-31 10:48:52.001161 +0200 CEST	deployed	k8ssandra-1.3.0    `
* Helm charts user-supplied values

`USER-SUPPLIED VALUES:
cassandra:
  allowMultipleNodesPerWorker: true
  cassandraLibDirVolume:
    size: 50Gi
    storageClass: do-block-storage-wait
  datacenters:
  - name: dc1
    racks:
    - name: default
    size: 1
  heap:
    newGenSize: 1G
    size: 1G
  resources:
    limits:
      cpu: 3000m
      memory: 5Gi
    requests:
      cpu: 3000m
      memory: 5Gi
  tolerations:
  - effect: NoSchedule
    key: app
    operator: Equal
    value: cassandra
  version: 4.0.0
kube-prometheus-stack:
  enabled: true
  grafana:
    adminPassword: redacted
    adminUser: redacted
medusa:
  bucketName:backups
  enabled: true
  storage: s3_compatible
  storage_properties:
    host: ams3.digitaloceanspaces.com
    port: 443
    secure: "True"
  storageSecret: prod-k8ssandra-medusa-key
stargate:
  cpuLimMillicores: 2000
  cpuReqMillicores: 200
  enabled: true
  heapMB: 1024
  replicas: 1` 

* Kubernetes version information:

`1.20.8-do.0`

* Kubernetes cluster kind:
Digitalocean Managed Kubernetes Cluster

**Additional context**

**Comment by jdonenine** [comment]
Hey @royrijkers are you still having this problem?  We can try to reproduce things on DO (it's not a platform that we use a lot), but the general operation is one that's well tested.

Would it be possible for you to give us the initial set of helm values deployed with and then also the upgrade set so that we can try the same changes?

**Comment by royrijkers** [comment]
Hi @jdonenine , Thanks for you reply. I do not have an exact copy of the initial helm values, I remember that I only changed the memory and cpu values.

Currently the error is a bit different and looks as follows: 
```ERROR [StorageServiceShutdownHook] 2021-10-04 07:14:55,049 StorageService.java:4942 - Caught an exception while draining 
java.lang.RuntimeException: javax.management.InstanceAlreadyExistsException: org.apache.cassandra.db:type=IndexTables,keyspace=dbkeyspace,table=access.access_customer_id
	at org.apache.cassandra.utils.MBeanWrapper$OnException.lambda$static$0(MBeanWrapper.java:175)
	at org.apache.cassandra.utils.MBeanWrapper$PlatformMBeanWrapper.registerMBean(MBeanWrapper.java:143)
	at org.apache.cassandra.utils.MBeanWrapper.registerMBean(MBeanWrapper.java:66)
	at org.apache.cassandra.utils.MBeanWrapper.registerMBean(MBeanWrapper.java:70)
	at org.apache.cassandra.db.ColumnFamilyStore.<init>(ColumnFamilyStore.java:447)
	at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:623)
	at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:597)
	at org.apache.cassandra.index.internal.CassandraIndex.setMetadata(CassandraIndex.java:227)
	at org.apache.cassandra.index.internal.CassandraIndex.<init>(CassandraIndex.java:84)
	at org.apache.cassandra.index.internal.composites.RegularColumnIndex.<init>(RegularColumnIndex.java:53)
	at org.apache.cassandra.index.internal.CassandraIndexFunctions$2.newIndexInstance(CassandraIndexFunctions.java:108)
	at org.apache.cassandra.index.internal.CassandraIndex.newIndex(CassandraIndex.java:762)
	at org.apache.cassandra.index.SecondaryIndexManager.createInstance(SecondaryIndexManager.java:773)
	at org.apache.cassandra.index.SecondaryIndexManager.createIndex(SecondaryIndexManager.java:215)
	at org.apache.cassandra.index.SecondaryIndexManager.addIndex(SecondaryIndexManager.java:278)
	at org.apache.cassandra.db.ColumnFamilyStore.<init>(ColumnFamilyStore.java:429)
	at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:623)
	at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:597)
	at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:588)
	at org.apache.cassandra.db.Keyspace.initCf(Keyspace.java:461)
	at org.apache.cassandra.db.Keyspace.<init>(Keyspace.java:355)
	at org.apache.cassandra.db.Keyspace.open(Keyspace.java:148)
	at org.apache.cassandra.db.Keyspace.open(Keyspace.java:124)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:785)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at org.apache.cassandra.service.StorageService.drain(StorageService.java:4871)
	at org.apache.cassandra.service.StorageService$1.runMayThrow(StorageService.java:759)
	at org.apache.cassandra.utils.WrappedRunnable.run(WrappedRunnable.java:28)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.management.InstanceAlreadyExistsException: org.apache.cassandra.db:type=IndexTables,keyspace=dbkeyspace,table=access.access_customer_id
	at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
	at org.apache.cassandra.utils.MBeanWrapper$PlatformMBeanWrapper.registerMBean(MBeanWrapper.java:139)
	... 28 common frames omitted```

**Comment by royrijkers** [comment]
currently i removed the keyspace 'projects_08753e97_e449_4c94_965a_aefbeb5a3af4' but the table 'access' exists on another keyspace now. now the error looks like this:

```INFO  [StorageServiceShutdownHook] 2021-10-04 07:58:21,262 Keyspace.java:386 - Creating replication strategy dbkeyspace params KeyspaceParams{durable_writes=true, replication=ReplicationParams{class=org.apache.cassandra.locator.SimpleStrategy, replication_factor=3}}
INFO  [StorageServiceShutdownHook] 2021-10-04 07:58:21,552 ColumnFamilyStore.java:399 - Initializing dbkeyspace.access
INFO  [StorageServiceShutdownHook] 2021-10-04 07:58:21,554 ColumnFamilyStore.java:399 - Initializing dbkeyspace.access.access_customer_id
ERROR [StorageServiceShutdownHook] 2021-10-04 07:58:21,970 StorageService.java:4942 - Caught an exception while draining 
java.lang.RuntimeException: javax.management.InstanceAlreadyExistsException: org.apache.cassandra.db:type=IndexTables,keyspace=dbkeyspace,table=access.access_customer_id
	at org.apache.cassandra.utils.MBeanWrapper$OnException.lambda$static$0(MBeanWrapper.java:175)
	at org.apache.cassandra.utils.MBeanWrapper$PlatformMBeanWrapper.registerMBean(MBeanWrapper.java:143)
	at org.apache.cassandra.utils.MBeanWrapper.registerMBean(MBeanWrapper.java:66)
	at org.apache.cassandra.utils.MBeanWrapper.registerMBean(MBeanWrapper.java:70)
	at org.apache.cassandra.db.ColumnFamilyStore.<init>(ColumnFamilyStore.java:447)
	at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:623)
	at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:597)
	at org.apache.cassandra.index.internal.CassandraIndex.setMetadata(CassandraIndex.java:227)
	at org.apache.cassandra.index.internal.CassandraIndex.<init>(CassandraIndex.java:84)
	at org.apache.cassandra.index.internal.composites.RegularColumnIndex.<init>(RegularColumnIndex.java:53)
	at org.apache.cassandra.index.internal.CassandraIndexFunctions$2.newIndexInstance(CassandraIndexFunctions.java:108)
	at org.apache.cassandra.index.internal.CassandraIndex.newIndex(CassandraIndex.java:762)
	at org.apache.cassandra.index.SecondaryIndexManager.createInstance(SecondaryIndexManager.java:773)
	at org.apache.cassandra.index.SecondaryIndexManager.createIndex(SecondaryIndexManager.java:215)
	at org.apache.cassandra.index.SecondaryIndexManager.addIndex(SecondaryIndexManager.java:278)
	at org.apache.cassandra.db.ColumnFamilyStore.<init>(ColumnFamilyStore.java:429)
	at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:623)
	at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:597)
	at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:588)
	at org.apache.cassandra.db.Keyspace.initCf(Keyspace.java:461)
	at org.apache.cassandra.db.Keyspace.<init>(Keyspace.java:355)
	at org.apache.cassandra.db.Keyspace.open(Keyspace.java:148)
	at org.apache.cassandra.db.Keyspace.open(Keyspace.java:124)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:785)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at org.apache.cassandra.service.StorageService.drain(StorageService.java:4871)
	at org.apache.cassandra.service.StorageService$1.runMayThrow(StorageService.java:759)
	at org.apache.cassandra.utils.WrappedRunnable.run(WrappedRunnable.java:28)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.management.InstanceAlreadyExistsException: org.apache.cassandra.db:type=IndexTables,keyspace=dbkeyspace,table=access.access_customer_id
	at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
	at org.apache.cassandra.utils.MBeanWrapper$PlatformMBeanWrapper.registerMBean(MBeanWrapper.java:139)
	... 28 common frames omitted```

**Comment by royrijkers** [comment]
does anyone have an idea how this can be solved? Is there a way I can make a backup without using Stargate?

**Comment by jsanda** [comment]
When you upgraded, did you change the memory and cpu of Stargate? If you made changes to Stargate configuration, then that would cause a rolling update of the Stargate Deployment. With a rolling update, we would (for a short period) have the old and new Stargate pods. I am wondering if that might be part of the root cause.

Have you tried completely disabling Stargate such that all Stargate pods are deleted and then re-enabling it? Worth a shot.
