### ISSUE TITLE
K8SSAND-1071 ⁃ Cassandra data dir fails to be created in 1.4.0

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra#1206]
## Bug Report

**Describe the bug**
When deploying K8ssandra 1.4.0 on GKE, Cassandra pods fail to start properly due to the following error:

```
Caused by: java.lang.IllegalStateException: Failed to mkdirs /opt/cassandra/data/data; unable to start server
	at org.apache.cassandra.config.DatabaseDescriptor.createAllDirectories(DatabaseDescriptor.java:1422)
	at org.apache.cassandra.db.commitlog.CommitLog.<init>(CommitLog.java:94)
	at org.apache.cassandra.db.commitlog.CommitLog.construct(CommitLog.java:77)
	at org.apache.cassandra.db.commitlog.CommitLog.<clinit>(CommitLog.java:64)
	... 3 common frames omitted
```

This is apparently due to newly added pod level `securityContext` entries. 
Removing those fixes the issue and Cassandra starts properly.

* Kubernetes cluster kind:
GKE

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1071) by [Unito](https://www.unito.io)
┆Reviewer: 5e66ca0cae59460cfb01a13c
┆fixVersions: k8ssndra-v1.4.1
┆friendlyId: K8SSAND-1071
┆priority: Medium

**Comment by lordphnx** [comment]
I had a todo listed for today to make this exact issue but for digital ocean, so thanks @adejanovski for saving me time! 
We "hacked" a "fix" by running the pod as root, but this seems like a much cleaner fix
