### ISSUE TITLE
K8SSAND-1175 ⁃ After a (medusa-based) backup, the restore procedure fails and crash-loops due to a token_map keyerror.

### ISSUE THREAD

**Issue by jschaul** [k8ssandra/k8ssandra#1260]
## Bug Report
**Describe the bug**

Restoring a backup fails with the following error as there seems to be a mismatch in the hostname(s) of how the backup job writes the tokenmap, and how the restore script expects the hostname to be in the tokenmap. Further, this mismatch isn't handled in the python code which simply crashes if an expected key isn't present:

Error:

```
│ Traceback (most recent call last):                                                                                                                                                         │
│   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main                                                                                                                     │
│     "__main__", mod_spec)                                                                                                                                                                  │
│   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code                                                                                                                                │
│     exec(code, run_globals)                                                                                                                                                                │
│   File "/home/cassandra/medusa/service/grpc/restore.py", line 78, in <module>                                                                                                              │
│     seeds, verify, keyspaces, tables, use_sstableloader)                                                                                                                                   │
│   File "/home/cassandra/medusa/restore_node.py", line 51, in restore_node                                                                                                                  │
│     keyspaces, tables)                                                                                                                                                                     │
│   File "/home/cassandra/medusa/restore_node.py", line 115, in restore_node_locally                                                                                                         │
│     tokens = get_node_tokens(node_fqdn, f)                                                                                                                                                 │
│   File "/home/cassandra/medusa/restore_node.py", line 339, in get_node_tokens                                                                                                              │
│     token = token_map[node_fqdn]['tokens']                                                                                                                                                 │
│ KeyError: 'galley-cassandra-galley-eks-eu-west-1a-sts-0'                                                                                                                                       │
│ stream closed  
```

Tokenmap contains:

`cat galley-tokenmap.json | jq 'keys[]'`

```
"172-10-2-158.galley-cassandra-galley-eks-service.databases.svc.cluster.local"
"172-10-3-177.galley-seed-service.databases.svc.cluster.local"
"localhost"
```

(each entry has the expected structure, e.g.)

```
{"localhost": {"tokens": [-1011741555770322217, -1029033082294974815, (...snip for brevity...)
```

But the python code during restore expects one key named `galley-cassandra-galley-eks-eu-west-1a-sts-0`.

This leads to an unrecoverable crash loop.

**To Reproduce**

1. Install the helm chart with cassandra.enabled=false but other operators enabled (see config overrides as below)
1. apply a kubernetes manifest for a configsecret and a cassandradatacenter resource (assuming existing s3 buckets and credentials are configured)
1. create a backup with `helm install my-backup2 k8ssandra/backup -n databases --set name=backup2,cassandraDatacenter.name=cassandra-galley-eks`
1. download the `backup2/meta/tokenmap.json` file from S3: it will have `localhost` and other FQDNs as its keys, but not `galley-cassandra-galley-eks-eu-west-1a-sts-0`
1. apply a restore procedure with `helm install restore k8ssandra/restore --set name=restore,backup.name=backup2,cassandraDatacenter.name=cassandra-galley-eks`
1. see the above error

**Expected behavior**

* The restore procedure should not error and the previous data re-appear. 
* Backup and restore should agree on the hostnames used: The restore code from medusa should not make wrong assumptions about hostnames that differ from the hostnames used by the backup job.
* The restore code from medusa should not crash when it doesn't find a given key

**Environment (please complete the following information):**

* Helm charts version info

```
k8ssandra          	databases          	4       	2022-01-12 22:09:35.698974626 +0100 CET	deployed	k8ssandra-1.4.1                                                                           	           
my-backup2         	databases          	1       	2022-01-12 22:16:00.364484746 +0100 CET	deployed	backup-0.26.0                                                                             	           
my-backup3         	databases          	1       	2022-01-13 12:32:15.334101047 +0100 CET	deployed	backup-0.26.0                                                                             	           
my-restore3        	databases          	1       	2022-01-13 12:38:17.790652042 +0100 CET	deployed	restore-0.27.1
```

* Helm charts user-supplied values

We created the helm release with `cassandra.enabled=false`

```yaml
cassandra:
  enabled: false
medusa:
  bucketName: medusa-backups-1
  enabled: true
  storage: s3
  storage_properties:
    region: eu-west-1
  storageSecret: medusa-bucket-key
reaper:
  enabled: true
stargate:
  enabled: false
```

And create a cassandradatacenter resource with the following contents:

First, the config, as kubernetes secret, used as `configSecret` inside the cassandradatacenter resource:

```yaml
apiVersion: v1
data:
  config: eyJjYXNzYW5kcmEteWFtbCI6eyJjcmVkZW50aWFsc191cGRhdGVfaW50ZXJ2YWxfaW5fbXMiOjM2MDAwMDAsImNyZWRlbnRpYWxzX3ZhbGlkaXR5X2luX21zIjozNjAwMDAwLCJudW1fdG9rZW5zIjoyNTYsInBlcm1pc3Npb25zX3VwZGF0ZV9pbnRlcnZhbF9pbl9tcyI6MzYwMDAwMCwicGVybWlzc2lvbnNfdmFsaWRpdHlfaW5fbXMiOjM2MDAwMDAsInJvbGVfbWFuYWdlciI6IkNhc3NhbmRyYVJvbGVNYW5hZ2VyIiwicm9sZXNfdXBkYXRlX2ludGVydmFsX2luX21zIjozNjAwMDAwLCJyb2xlc192YWxpZGl0eV9pbl9tcyI6MzYwMDAwMH0sImNsdXN0ZXItaW5mbyI6eyJuYW1lIjoiZ2FsbGV5Iiwic2VlZHMiOiJnYWxsZXktc2VlZC1zZXJ2aWNlLGdhbGxleS1jYXNzYW5kcmEtZ2FsbGV5LWVrcy1hZGRpdGlvbmFsLXNlZWQtc2VydmljZSJ9LCJkYXRhY2VudGVyLWluZm8iOnsiZ3JhcGgtZW5hYmxlZCI6MCwibmFtZSI6ImNhc3NhbmRyYS1nYWxsZXktZWtzIiwic29sci1lbmFibGVkIjowLCJzcGFyay1lbmFibGVkIjowfSwianZtLW9wdGlvbnMiOnsiYWRkaXRpb25hbC1qdm0tb3B0cyI6W10sImhlYXBfc2l6ZV95b3VuZ19nZW5lcmF0aW9uIjoiNTEyME0iLCJpbml0aWFsX2hlYXBfc2l6ZSI6IjUxMjBNIiwibWF4X2hlYXBfc2l6ZSI6IjUxMjBNIn19
kind: Secret
metadata:
  creationTimestamp: "2022-01-12T13:13:39Z"
  name: galley-cassandra-galley-eks-config
  namespace: databases
  ownerReferences:
  - apiVersion: cassandra.datastax.com/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: CassandraDatacenter
    name: cassandra-galley-eks
    uid: a6babfbd-a8e5-4479-aabb-0e08fe6279bd
  resourceVersion: "32175131"
  uid: 98799fba-b3aa-45ac-8e6c-fb1a17ae74bb
type: Opaque
```

base64 decoded:

`kubectl -n databases get secret galley-cassandra-galley-eks-config -o jsonpath="{.data.config}" |base64 -d | jq`

```json
{
  "cassandra-yaml": {
    "credentials_update_interval_in_ms": 3600000,
    "credentials_validity_in_ms": 3600000,
    "num_tokens": 256,
    "permissions_update_interval_in_ms": 3600000,
    "permissions_validity_in_ms": 3600000,
    "role_manager": "CassandraRoleManager",
    "roles_update_interval_in_ms": 3600000,
    "roles_validity_in_ms": 3600000
  },
  "cluster-info": {
    "name": "galley",
    "seeds": "galley-seed-service,galley-cassandra-galley-eks-additional-seed-service"
  },
  "datacenter-info": {
    "graph-enabled": 0,
    "name": "cassandra-galley-eks",
    "solr-enabled": 0,
    "spark-enabled": 0
  },
  "jvm-options": {
    "additional-jvm-opts": [],
    "heap_size_young_generation": "5120M",
    "initial_heap_size": "5120M",
    "max_heap_size": "5120M"
  }
}
```

and the datacenter has these values (before a restore is attempted):

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  annotations:
    cassandra.datastax.com/config-hash: gLdDfge5UN0SBW6TqDBvenGro/AHF3q8VAI4ImOcS38=
  creationTimestamp: "2022-01-12T13:10:38Z"
  finalizers:
  - finalizer.cassandra.datastax.com
  generation: 3
  name: cassandra-galley-eks
  namespace: databases
  resourceVersion: "35476374"
  uid: a6babfbd-a8e5-4479-aabb-0e08fe6279bd
spec:
  additionalSeeds: []
  additionalServiceConfig:
    dcService:
      additionalAnnotations:
        external-dns.alpha.kubernetes.io/hostname: k8ssandra-eks-galley-staging.zinfra.io
        external-dns.alpha.kubernetes.io/ttl: 1m
  clusterName: galley
  configBuilderImage: docker.io/datastax/cass-config-builder:1.0.4
  configSecret: cassandra-config-overrides-galley
  dockerImageRunsAsCassandra: true
  managementApiAuth:
    insecure: {}
  nodeSelector:
    wire.com/role: cassandra-galley
  podTemplateSpec:
    spec:
      containers:
      - env:
        - name: LOCAL_JMX
          value: "no"
        - name: METRIC_FILTERS
          value: deny:org.apache.cassandra.metrics.Table deny:org.apache.cassandra.metrics.table
            allow:org.apache.cassandra.metrics.table.live_ss_table_count allow:org.apache.cassandra.metrics.Table.LiveSSTableCount
            allow:org.apache.cassandra.metrics.table.live_disk_space_used allow:org.apache.cassandra.metrics.table.LiveDiskSpaceUsed
            allow:org.apache.cassandra.metrics.Table.Pending allow:org.apache.cassandra.metrics.Table.Memtable
            allow:org.apache.cassandra.metrics.Table.Compaction allow:org.apache.cassandra.metrics.table.read
            allow:org.apache.cassandra.metrics.table.write allow:org.apache.cassandra.metrics.table.range
            allow:org.apache.cassandra.metrics.table.coordinator allow:org.apache.cassandra.metrics.table.dropped_mutations
        name: cassandra
        securityContext: {}
        volumeMounts:
        - mountPath: /etc/podinfo
          name: podinfo
      - env:
        - name: MEDUSA_MODE
          value: GRPC
        - name: CQL_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: k8ssandra-medusa
        - name: CQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: k8ssandra-medusa
        image: docker.io/k8ssandra/medusa:0.11.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50051
          initialDelaySeconds: 10
        name: medusa
        ports:
        - containerPort: 50051
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50051
          initialDelaySeconds: 5
        securityContext: {}
        volumeMounts:
        - mountPath: /etc/medusa
          name: k8ssandra-medusa
        - mountPath: /etc/cassandra
          name: cassandra-config
        - mountPath: /var/lib/cassandra
          name: server-data
        - mountPath: /etc/medusa-secrets
          name: medusa-bucket-key
      initContainers:
      - args:
        - -c
        - cp -r /etc/cassandra/* /cassandra-base-config/
        command:
        - /bin/sh
        image: k8ssandra/cass-management-api:3.11.10-v0.1.27
        imagePullPolicy: IfNotPresent
        name: base-config-init
        securityContext: {}
        volumeMounts:
        - mountPath: /cassandra-base-config/
          name: cassandra-config
        - mountPath: /opt/metrics-collector/config/
          name: cassandra-metrics-coll-config
        - mountPath: /tmp/
          name: cassandra-tmp
        - mountPath: /etc/reaper/
          name: reaper-config
      - name: server-config-init
        securityContext: {}
      - args:
        - /bin/sh
        - -c
        - echo "$REAPER_JMX_USERNAME $REAPER_JMX_PASSWORD" > /config/jmxremote.password
          && echo "$SUPERUSER_JMX_USERNAME $SUPERUSER_JMX_PASSWORD" >> /config/jmxremote.password
        env:
        - name: REAPER_JMX_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: k8ssandra-reaper-jmx
        - name: REAPER_JMX_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: k8ssandra-reaper-jmx
        - name: SUPERUSER_JMX_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: k8ssandra-superuser
        - name: SUPERUSER_JMX_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: k8ssandra-superuser
        image: docker.io/busybox:1.33.1
        imagePullPolicy: IfNotPresent
        name: jmx-credentials
        securityContext: {}
        volumeMounts:
        - mountPath: /config
          name: server-config
      - env:
        - name: MEDUSA_MODE
          value: RESTORE
        - name: CQL_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: k8ssandra-medusa
        - name: CQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: k8ssandra-medusa
        image: docker.io/k8ssandra/medusa:0.11.3
        imagePullPolicy: IfNotPresent
        name: medusa-restore
        volumeMounts:
        - mountPath: /etc/medusa
          name: k8ssandra-medusa
        - mountPath: /etc/cassandra
          name: server-config
        - mountPath: /var/lib/cassandra
          name: server-data
        - mountPath: /etc/podinfo
          name: podinfo
        - mountPath: /etc/medusa-secrets
          name: medusa-bucket-key
      volumes:
      - emptyDir: {}
        name: cassandra-config
      - emptyDir: {}
        name: cassandra-metrics-coll-config
      - emptyDir: {}
        name: cassandra-tmp
      - emptyDir: {}
        name: reaper-config
      - downwardAPI:
          items:
          - fieldRef:
              fieldPath: metadata.labels
            path: labels
        name: podinfo
      - configMap:
          items:
          - key: medusa.ini
            path: medusa.ini
          name: k8ssandra-medusa
        name: k8ssandra-medusa
      - name: medusa-bucket-key
        secret:
          secretName: medusa-bucket-key
  racks:
  - name: eu-west-1a
    nodeAffinityLabels:
      topology.kubernetes.io/zone: eu-west-1a
  - name: eu-west-1b
    nodeAffinityLabels:
      topology.kubernetes.io/zone: eu-west-1b
  - name: eu-west-1c
    nodeAffinityLabels:
      topology.kubernetes.io/zone: eu-west-1c
  resources:
    limits:
      cpu: 1200m
      memory: 10240Mi
    requests:
      cpu: 1200m
      memory: 10240Mi
  serverImage: k8ssandra/cass-management-api:3.11.10-v0.1.27
  serverType: cassandra
  serverVersion: 3.11.10
  size: 3
  storageConfig:
    cassandraDataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
      storageClassName: gp2
  systemLoggerImage: docker.io/k8ssandra/system-logger:6c64f9c4
  tolerations:
  - key: wire.com/role
    value: cassandra
  users:
  - secretName: k8ssandra-reaper
    superuser: true
  - secretName: k8ssandra-medusa
    superuser: true
status:
  cassandraOperatorProgress: Ready
  conditions:
  - lastTransitionTime: "2022-01-12T15:58:19Z"
    message: ""
    reason: ""
    status: "False"
    type: ScalingUp
  - lastTransitionTime: "2022-01-12T13:17:37Z"
    message: ""
    reason: ""
    status: "False"
    type: Stopped
  - lastTransitionTime: "2022-01-12T13:17:37Z"
    message: ""
    reason: ""
    status: "False"
    type: ReplacingNodes
  - lastTransitionTime: "2022-01-12T15:58:19Z"
    message: ""
    reason: ""
    status: "False"
    type: Updating
  - lastTransitionTime: "2022-01-12T13:17:37Z"
    message: ""
    reason: ""
    status: "False"
    type: RollingRestart
  - lastTransitionTime: "2022-01-12T13:17:37Z"
    message: ""
    reason: ""
    status: "False"
    type: Resuming
  - lastTransitionTime: "2022-01-12T13:17:37Z"
    message: ""
    reason: ""
    status: "False"
    type: ScalingDown
  - lastTransitionTime: "2022-01-12T13:17:37Z"
    message: ""
    reason: ""
    status: "True"
    type: Valid
  - lastTransitionTime: "2022-01-12T13:17:39Z"
    message: ""
    reason: ""
    status: "True"
    type: Initialized
  - lastTransitionTime: "2022-01-12T13:17:39Z"
    message: ""
    reason: ""
    status: "True"
    type: Ready
  lastServerNodeStarted: "2022-01-12T15:57:36Z"
  nodeStatuses:
    galley-cassandra-galley-eks-eu-west-1a-sts-0:
      hostID: 64e9f3ca-f69f-469d-97ee-236ecad6134d
    galley-cassandra-galley-eks-eu-west-1b-sts-0:
      hostID: 792d59c3-ca6a-427a-82e3-98401923196c
    galley-cassandra-galley-eks-eu-west-1c-sts-0:
      hostID: c2cf345c-c9ce-4365-b043-b3e7bf537643
  observedGeneration: 3
  quietPeriod: "2022-01-17T14:14:00Z"
  superUserUpserted: "2022-01-17T14:13:55Z"
  usersUpserted: "2022-01-17T14:13:55Z"
```

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

Amazon EKS with terraform

```
module "eks" {
  source          = "terraform-aws-modules/eks/aws"
  version         = "17.1.0"
```

**Additional context**

`exec`ing into a pod and using some of the python commands used in the backup/restore procedures shows the tokenmap and fqdn as follows:

{code:python}
python3
>>> import socket
>>> socket.getfqdn()
'galley-cassandra-galley-eks-eu-west-1a-sts-0'
>>> socket.gethostbyname(socket.getfqdn())
'172.10.1.90'
>>> socket.getfqdn(socket.gethostbyname(socket.getfqdn()))
'galley-cassandra-galley-eks-eu-west-1a-sts-0'

>>> from medusa.cassandra_utils import Cassandra
>>> from medusa.config import load_config
>>> from pathlib import Path
>>> from collections import defaultdict
>>> c = load_config(defaultdict(lambda: None), Path("/etc/medusa/medusa.ini"))
>>> cass = Cassandra(c)
>>> sess = cass.new_session()
>>> sess.tokenmap().keys()

dict_keys(['localhost', '172-10-2-77.galley-cassandra-galley-eks-all-pods-service.databases.svc.cluster.local', '172-10-3-116.galley-cassandra-galley-eks-service.databases.svc.cluster.local'])

>>> sess.tokenmap()
{'localhost': {'tokens': [-1039828990371650753, ~~1072927566880296815, ~~1139232322414697295,~~-~~ 1152133842071369065, ~~1217072953872418611,~~- 1260421536329538701, ~~1373682471216984502,~~- 145426759316082616, ~~1466806541682025007,~~- 1500442854622108136, ~~1534983379839219754,~~- 1559726053876218602, ~~1614729408967139280,~~- 161699399452299550, ~~1620306055711359285,~~- 1747387244991831639, ~~180274595359708838,~~- 1856066503151057339, ~~1953920202883409941,~~- 2224338953167968917, ~~2314777479818987263,~~- 2326249638151821601, ~~2446986873589987901,~~- 246911408010759668, ~~2678148288908111173,~~- 2682636572509271728, ~~2723855292798915433,~~- 2753612797184312111, ~~2830057370783589947,~~- 2880537458045583043, ~~2893700049649147788,~~- 2918344248401903982, ~~3188400208535995204,~~- 3441033790090973011, ~~3481738999779319384,~~- 3485385948364244578, ~~349393580111323049,~~- 3500911656041258733, ~~3517568469286884658,~~- 3550412394753406407, ~~3663716584430443605,~~- 3690400801513194413, ~~3794424465465905399,~~- 3795284706822975352, ~~3820887135113498807,~~- 3830573275137526426, ~~3908657160062660007,~~- 3930948663370016991, ~~4014955096860623296,~~- 402178341202824893, ~~4080595567291396362,~~- 4245145267610825036, ~~4255931855482496091,~~- 4266530612817907517, ~~4306999102506062647,~~- 4389871411694487835, ~~4436710220507864223,~~- 4447371810284315467, ~~4456945505345088441,~~- 4602670800758170053, ~~4685724356161073397,~~- 470894886441252411, ~~4712914142461448567,~~- 4723103798587879448, ~~4985942871879749243,~~- 4994950079038550098, ~~5046298922860590143,~~- 5153682317944283973, ~~5209339099109113472,~~- 5250944583414111763, ~~5273830298769547608,~~- 5298243574684639227, ~~548207825213963763,~~- 5536620427474779522, ~~5668997855685906417,~~- 5683072072848801726, ~~5726747093263538370,~~- 5752487859917270884, ~~5771083738861142868,~~- 5772165467036856788, ~~5853402554865502681,~~- 5977845919630270364, ~~6005573435889232200,~~- 6135625072429274874, ~~6139553846533184336,~~- 6217226093218211962, ~~627848094718658412,~~- 6399817841600711126, ~~640253212380904616,~~- 6645263824093151500, ~~6666711514267859941,~~- 6718571448330553526, ~~6916105528752462456,~~- 6988028692776702357, ~~701218581874101607,~~- 7192127206668125316, ~~7235352863887268172,~~- 7353928597823771193, ~~7375219291955452640,~~- 7472952596594578396, ~~7558910551112189667,~~- 765832335271448271, ~~7709770746024411903,~~- 7713933953296438144, ~~7815598111427657966,~~- 7856509909312956085, ~~7880106393993642934,~~- 7915631071466016964, ~~7916911122317894389,~~- 7975296921537007691, ~~799700997551218499,~~- 8000556012154697165, ~~8070902637362825560,~~- 8111731741261692077, ~~8132768713382860919,~~- 8137652278865326889, ~~8246494678040691024,~~- 8285552441874400228, ~~8295346382754845430,~~- 8358802785682670979, ~~8400539883613857908,~~- 8476366162274021179, ~~8589976749323329543, ~~8592713098423000711, ~~8622069066947874762, ~~8738833931362774402, ~~876824006220540400, ~~879314305861771352, ~~8814109264529628993, ~~8817526414072791732, ~~9027492391521719857, ~~9038336927106413052, ~~9158116799142385943, 1145440385695612107, 1305242797353780864, 1319292039061529380, 1340447737111416481, 1539560970071247271, 1550514281517788693, 1563803274588686805, 1721917472921595867, 186847519441212457, 1885548613249775373, 1919685508307512655, 1966042438885919899, 221637741432616457, 2410406289327121111, 2440755124107083522, 2636399004861254907, 2797180035394011763, 2845372583749404995, 2889251855153080884, 2987504777600802150, 3125672789560624097, 3135626567885368784, 3254803701183320739, 330606065864557638, 331755992549040052, 3414135615629588570, 3477710421374910832, 3549640613353965051, 3784445164330838909, 3975515871971800019, 4083346050041544655, 4111246424749925040, 4119439946003984323, 417715575464648449, 4232851553525038493, 4260551869741649345, 4322288958192244860, 4383456123231913058, 438521983405640039, 4414369501974996169, 455231189482785742, 4678676514294328050, 4829301091383889341, 4851517119409973906, 4873164993360005375, 4921356093613923193, 4938664378458597070, 4952503084566528265, 4957388702275112678, 4998351559584137602, 5044296819186422109, 5113626145099128874, 512723928698593344, 528913225941486773, 5309765209232773738, 5312273140989098094, 5416873618910062519, 5436442741858615528, 5581923775845550042, 5683771204313524838, 5687499184400448448, 5708786638204488794, 5755744355890776149, 5768477286490734578, 6006582372681079404, 6027387130912078748, 6037793436481033843, 6069035753109072778, 6297036160482153967, 6308087644210618789, 6321173098417106990, 6489807017270617765, 6614843595481117857, 6630323967780989047, 6644566207333277419, 6648574961076090020, 6684760096248247613, 6687580364301945957, 6737434894341737964, 679964253323792338, 6810826932114889084, 6813913431379554640, 6815639993116238440, 6835130600417301520, 683667923276889512, 6846641494239240802, 6906420442817757673, 6932232239719359842, 7037789141772433917, 7192087738402600501, 7201943794843157301, 7257725665141189927, 7319087615563356542, 7472753715070669278, 7517576034821302457, 7526495534683645203, 7668212789850212784, 7687147478609191922, 7761512458218694962, 7882747796817818677, 7886561898683638853, 7977667535758293326, 7988236252366073307, 8134459096556857479, 8234459989597636385, 8299515765675099302, 838241938168295903, 8399270254850844216, 8433955900589781717, 8485228957805135196, 8488895600153215272, 8661590841498842721, 8693822283210803476, 8806258493393690450, 8990786332547760304, 911257504527743421, 911282755464538150, 9158194361872191133, 9160599342557800, 9194248783447795838, 9208507065921969534, 954367930773795670, 96444003920419744], 'is_up': True}, '172~~----------~~---------~~--------~~-------~~------~~-----~~----~~---~~--~~\-~~------------------------------------------------------------------10----------2---------77.galley--------cassandra-------galley------eks-----all----pods---service.databases.svc.cluster.local': {'tokens': [--1045565058386177880,- 1051466891318652920, ~~1082050141250200876,~~ 1146624979094049466, ~~1175048961524488697,~~ 124764047225357096, ~~1288164785833506181,~~ 1320787327536235978, ~~1404227882532110091,~~ 1432638600592202578, ~~173597591689883631,~~ 1801991657518017131, ~~1869035002488245888,~~ 1879801561855380230, ~~1924319901467300430,~~ 1930515225017223745, ~~1935057489030205364,~~ 1945759244010373978, ~~195570664596016859,~~ 198264222718771812, ~~214022754751942352,~~ 2296616236687795893, ~~2307010637857153541,~~ 2344698224341700216, ~~238702792945461500,~~ 2413610507694250512, ~~274342868569277096,~~ 2749815178155004400, ~~2750864555712914450,~~ 2875814529858417493, ~~2929777910535611033,~~ 3006311179788111692, ~~3021487363342648949,~~ 309312155501498361, ~~3104718835238246873,~~ 3237784857664809094, ~~3285240129353301621,~~ 3365316961528775024, ~~3561086130934995331,~~ 3645182312232074393, ~~3688599439558140573,~~ 3774765556509776409, ~~3778466770798772409,~~ 3999771117728664266, ~~4023604551463839181,~~ 4038941951142466672, ~~4247239946635111806,~~ 43529779763557624, ~~4368805307114904505,~~ 4374570914877723889, ~~445906404970633225,~~ 4529626961381735520, ~~4663695406688158370,~~ 4776720756657230094, ~~4833525362361462320,~~ 4845083008088203485, ~~4854041083137351069,~~ 4882947288793981674, ~~4951774331154233428,~~ 5102466519106675394, ~~5105080930264720351,~~ 5111242565501204913, ~~5120625967042829908,~~ 5208743476847306261, ~~5222337007721291514,~~ 5295349370548984115, ~~5369909475123905921,~~ 5493495761748608136, ~~5512965682995837989,~~ 5594927991159284891, ~~5818978501791739569,~~ 5877802279886058269, ~~6013945239322524439,~~ 6190934755231779524, ~~6398565104160380076,~~ 6427642964141988685, ~~6438268383597474541,~~ 6486857600651899722, ~~651515068396915057,~~ 6546644696051374399, ~~6600707558310264027,~~ 6635872060313973904, ~~6817819104909783518,~~ 6892375374799398683, ~~6893001136502330339,~~ 6898297690048943422, ~~6922145781148910737,~~ 6983379326537443389, ~~7053307396877573176,~~ 7155602679935161890, ~~7196001999242228210,~~ 7242788577566602725, ~~7298294057462740336,~~ 7306414882013214351, ~~7359014145915220624,~~ 7432327085132821533, ~~744483747322220612,~~ 7564135160971467979, ~~7813482990076473621,~~ 7908890837424712166, ~~7948143347143040169,~~ 7949803154954176241, ~~7955775075633232858,~~ 8012895840603825089, ~~8029506337571674262,~~ 8044591751909560084, ~~8156898736614452759,~~ 8214037225339816229, ~~8361197399238137924,~~ 8600355071196472556, ~~8736682714790869970,~~ 8789193442418014322, ~~8867692333130251622,~~ 8906214820802835882, ~~8909870678384804352, ~~8931485246725609139, ~~8972612273584788049, ~~8998739422055883119, ~~9041715058586732099, ~~9061072142564971547, ~~9123146739706828145, ~~9189442608844539951, ~~931559299492813106, 1019026706377774341, 1049364609066454389, 1181355691337191905, 1183874536678894398, 129763136666149672, 1315073358254316045, 1334536616101245506, 1418474361876186564, 1484650594857614719, 1493701171806177468, 1667530250110218195, 176621445970870103, 1768493343306165431, 185209859148028671, 2073511318242710175, 2179587483003478988, 2183045200982596004, 2229473362179685412, 2313984200366107236, 2383754993908587527, 2500472904213012833, 2626188688525130975, 2769571105912738566, 2844012059933822333, 2891870994950603235, 3113382339987496636, 3172968912212373165, 3185333795201781810, 320791327593309409, 3301736858626184410, 3306774173632363381, 3336167519749791723, 3374020862516117408, 3447909542592988168, 3572892019518112604, 3589969627179795697, 3610580822970714876, 3656924782415701887, 3660168436077588286, 367978283902523020, 369411260087710348, 3805882139553536092, 3858196935432883960, 3900142132101376303, 4052158587631488758, 4088672009970747402, 4130801274842425229, 4251021173821092909, 431773093965072694, 4329790925390509593, 4472797231149283676, 4513426830649615134, 457722284816866344, 4645725970020587816, 4649684165305478395, 4662934424401273274, 4690412895767099340, 4734020825562210339, 4759097626376794245, 4864352069413219294, 4873314314476659469, 488293000075002379, 508405552519275639, 5304522710227584576, 5309478456866898505, 5546556891593901393, 558361449052325713, 5587828788277132106, 559938421268413983, 5624000436547884825, 5670238383852745660, 5746815218373219269, 5841418730928216223, 5904529265118107870, 5929554483433253535, 5950579790847129015, 595549551498631832, 5973102410735044348, 600977218579322335, 6090236145306457866, 6157835464600570170, 6162276615967435036, 6170653129195951245, 6172802693007280305, 6238157055002451277, 6254188179325847245, 6318494018571822174, 6333068976155223392, 6384581860278032804, 6481037463189988981, 6659616598694863307, 6671503220379376560, 6682538189321226275, 6795551335836859977, 6802100499623680426, 7074644409602960096, 7086857700613627266, 7096455470754747332, 7150697219336673379, 7262475659838356922, 7273298279005457492, 7291260057806162122, 7322141969787644695, 7337865978970037906, 7392746440865425383, 7498673241237101622, 7531040722102863904, 7567466579033930085, 758942770621648414, 7610174766495552508, 7668791904138103581, 7823072385318809072, 787362981535227618, 8052690327815771801, 81961068069494852, 8338757985091245860, 8409856586418964284, 8434506245419238893, 8536787171147948847, 8578702673623602915, 8589169480119849821, 8660957127306622494, 8681983163886866657, 8749118217394325149, 8759432455451047263, 8818785046641713105, 8892117281226254077, 9012007503977454043, 9172269519077113128, 92434102417738754, 960581666873784248, 980747269658287363, 989866559166026334], 'is_up': True}, '172~~--------~~-------~~------~~-----~~----~~---~~--~~\-~~------------------------------------10--------3-------116.galley------cassandra-----galley----eks---service.databases.svc.cluster.local': {'tokens': [--1057317867534855419,- 111268635338623247, ~~1235149537261494318,~~ 1260265722000152448, ~~1386723428805513983,~~ 1501868974933236757, ~~1790497119217986071,~~ 1820228681432395791, ~~1891506597654571820,~~ 1988955390732879991, ~~2033092640348807576,~~ 2045256299349929742, ~~2075638950295386987,~~ 2111969706043188413, ~~2255872118121793962,~~ 2314872003945202663, ~~2550959978316775310,~~ 2595298466047691301, ~~2620075201112711449,~~ 2717674250972038818, ~~2742031461070748247,~~ 2784171305383140131, ~~2796180307075303238,~~ 2915289009370326028, ~~2957670209597883584,~~ 298987647454314766, ~~3010652746014921574,~~ 3029743652330384547, ~~313686194122291731,~~ 3190828892196573806, ~~321092539936968021,~~ 3332056852738097841, ~~3434981104804878061,~~ 352507035486202537, ~~3544778157372246723,~~ 3662373807590668690, ~~3691258691591223559,~~ 3885262277022258915, ~~3887787067854830556,~~ 3943009312690436065, ~~4015528148315598965,~~ 4186862316140584938, ~~4374481697362842539,~~ 4438257669830502062, ~~4485890261731857932,~~ 4525752762641601908, ~~4538591245380688250,~~ 4565737018843232180, ~~4580298926710615293,~~ 4610790950395606817, ~~469979588707867593,~~ 4823447509023146018, ~~4833444911806361493,~~ 5018299361684493789, ~~5127074198466870543,~~ 5178130526035906203, ~~5245104958200513951,~~ 5351541141854093692, ~~53965562874633595,~~ 5398395762918742502, ~~5407790002570049409,~~ 5485687179740922915, ~~5613361850025577137,~~ 566061439128282428, ~~5958024515075981506,~~ 5999953327142157533, -60013578

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1175) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1175
┆priority: Medium

**Comment by jschaul** [comment]
It turns out the `cassandra` container did not have the `/etc/cassandra/` volume mount that is shared with the `medusa` containers. Maybe that explains the differing hostnames seen. We fixed that and now restores work.
Sorry for the noise. (but these problems are quite hard to debug actually...)
