### ISSUE TITLE
K8SSAND-1266 ⁃ medusa initiation with gcs is failing

### ISSUE THREAD

**Issue by alokhom** [k8ssandra/k8ssandra#1301]
**the k8ssandra medusa is failing to connect to the gcs**

what would be the gcs bucketName  representation if you have a subfolder inside a bucket ?

**What did you do?**
I defined the yaml config in cassandra.yaml 
The below is failing

```
  values:
    medusa:
      enabled: true
      multiTenant: true
      storage: google_storage
      bucketName: "containername/subfolder-name"
      storageSecret: google-storage-s3-json
```

 the credentials are correct and i am able to use restic to push files to the sub-folder. 
 But with medusa i get this error.

```
WARNING:root:Forcing use_sudo to False because Kubernetes mode is enabled
WARNING:root:Forcing use_sudo to False because Kubernetes mode is enabled
INFO:root:Init service
[2022-02-21 16:48:30,872] INFO: Init service
DEBUG:root:Loading storage_provider: google_storage
[2022-02-21 16:48:30,872] DEBUG: Loading storage_provider: google_storage
INFO:libcloud.common.google:Failed to read cached auth token from file "/home/cassandra/.google_libcloud_auth.xxxxxstagingcassandramedusa@xxxxxxonline.iam.gserviceaccount.com": [Errno 2] No such file or directory: '/home/cassandra/.google_libcloud_auth.xxxxxstagingcassandramedusa@xxxxxxonline.iam.gserviceaccount.com'
[2022-02-21 16:48:30,872] INFO: Failed to read cached auth token from file "/home/cassandra/.google_libcloud_auth.xxxxxstagingcassandramedusa@xxxxxxonline.iam.gserviceaccount.com": [Errno 2] No such file or directory: '/home/cassandra/.google_libcloud_auth.xxxxxxstagingcassandramedusa@xxxxxxonline.iam.gserviceaccount.com'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): accounts.google.com:443
[2022-02-21 16:48:30,919] DEBUG: Starting new HTTPS connection (1): accounts.google.com:443
DEBUG:urllib3.connectionpool:https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
[2022-02-21 16:48:30,952] DEBUG: https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): storage.googleapis.com:443
[2022-02-21 16:48:30,958] DEBUG: Starting new HTTPS connection (1): storage.googleapis.com:443
DEBUG:urllib3.connectionpool:https://storage.googleapis.com:443 "HEAD /gcloudstagingXXXXXXXX/cassandra HTTP/1.1" 404 0
[2022-02-21 16:48:31,015] DEBUG: https://storage.googleapis.com:443 "HEAD /gcloudstagingXXXXXXXXX/cassandra HTTP/1.1" 404 0
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/cassandra/medusa/service/grpc/server.py", line 297, in <module>
    server.serve()
  File "/home/cassandra/medusa/service/grpc/server.py", line 60, in serve
    medusa_pb2_grpc.add_MedusaServicer_to_server(MedusaService(config), self.grpc_server)
  File "/home/cassandra/medusa/service/grpc/server.py", line 99, in __init__
    self.storage = Storage(config=self.config.storage)
  File "/home/cassandra/medusa/storage/__init__.py", line 72, in __init__
    self.storage_driver = self._connect_storage()
  File "/home/cassandra/medusa/storage/__init__.py", line 78, in _connect_storage
    google_storage = GoogleStorage(self._config)
  File "/home/cassandra/medusa/storage/abstract_storage.py", line 40, in __init__
    self.bucket = self.driver.get_container(container_name=config.bucket_name)
  File "/home/cassandra/.local/lib/python3.6/site-packages/libcloud/storage/drivers/s3.py", line 360, in get_container
    container_name=container_name)
libcloud.storage.types.ContainerDoesNotExistError: <ContainerDoesNotExistError in <libcloud.storage.drivers.google_storage.GoogleStorageDriver object at 0x7f5123d01208>, container=gcloudstagingxxxxxxx/cassandra, value=None>
```

**Did you expect to see some different?**
the connection to be successful to gcs.
Using the same credentials and restic it works. 

**Environment**
gke 3 node. k8sssandra cluster with medusa. 

* Helm charts version
k8ssandra 1.4.1

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1266) by [Unito](https://www.unito.io)
┆fixVersions: k8ssandra-v1.5.0
┆friendlyId: K8SSAND-1266
┆priority: Medium

**Comment by alokhom** [comment]
I could add the folder to the medusa mentioning it as  the follows and it worked to connect to the gcs from medusa. 
```
  values:
    medusa:
      enabled: true
      multiTenant: true
      storage: google_storage
      bucketName: "containername:subfolder-name"
      storageSecret: google-storage-s3-json
```

but the files are not uploading as seen below in the medusa logs. 
```
DEBUG:urllib3.connectionpool:https://storage.googleapis.com:443 "PUT /container-name:folder-name/.cassandra/main-cluster-dc1-rack1-sts-0/medusa-daily-20220221174950/meta/schema.cql HTTP/1.1" 400 214
[2022-02-21 17:49:53,398] DEBUG: https://storage.googleapis.com:443 "PUT /container-name:folder-name/.cassandra/main-cluster-dc1-rack1-sts-0/medusa-daily-20220221174950/meta/schema.cql HTTP/1.1" 400 214
DEBUG:urllib3.connectionpool:https://storage.googleapis.com:443 "PUT /container-name:folder-name/.cassandra/main-cluster-dc1-rack1-sts-0/medusa-daily-20220221174950/meta/schema.cql HTTP/1.1" 400 214
[2022-02-21 17:50:13,502] DEBUG: https://storage.googleapis.com:443 "PUT /container-name:folder-name/.cassandra/main-cluster-dc1-rack1-sts-0/medusa-daily-20220221174950/meta/schema.cql HTTP/1.1" 400 214
DEBUG:urllib3.connectionpool:https://storage.googleapis.com:443 "PUT /container-name:folder-name/.cassandra/main-cluster-dc1-rack1-sts-0/medusa-daily-20220221174950/meta/schema.cql HTTP/1.1" 400 214
[2022-02-21 17:50:53,651] DEBUG: https://storage.googleapis.com:443 "PUT /container-name:folder-name/.cassandra/main-cluster-dc1-rack1-sts-0/medusa-daily-20220221174950/meta/schema.cql HTTP/1.1" 400 214
```

and in the medusa-controller logs it shows after some time...
```
2022-02-21T17:34:48.728Z	ERROR	controllers.CassandraBackup	backup failed	{"CassandraPod": "main-cluster-dc1-rack2-sts-0", "error": "rpc error: code = Internal desc = failed to create backups: <LibcloudError in <libcloud.storage.drivers.google_storage.GoogleStorageDriver object at 0x7ff8e0049eb8> 'Unexpected status code, status_code=400'>"}
2022-02-21T17:34:49.025Z	ERROR	controllers.CassandraBackup	backup failed	{"CassandraPod": "main-cluster-dc1-rack3-sts-0", "error": "rpc error: code = Internal desc = failed to create backups: <LibcloudError in <libcloud.storage.drivers.google_storage.GoogleStorageDriver object at 0x7f32487be668> 'Unexpected status code, status_code=400'>"}
2022-02-21T17:34:50.084Z	ERROR	controllers.CassandraBackup	backup failed	{"CassandraPod": "main-cluster-dc1-rack1-sts-0", "error": "rpc error: code = Internal desc = failed to create backups: <LibcloudError in <libcloud.storage.drivers.google_storage.GoogleStorageDriver object at 0x7ff1684d92e8> 'Unexpected status code, status_code=400'>"}
2022-02-21T17:34:50.084Z	INFO	controllers.CassandraBackup	finished backup operations
```

the credential has all the permissions that were added from the link https://github.com/thelastpickle/cassandra-medusa/blob/master/docs/permissions-setup.md and i have followed the documentation on https://github.com/thelastpickle/cassandra-medusa/blob/master/docs/gcs_setup.md. Just that i donot maje a file in /etc/medusa and instead i see a configMap is made for medusa.ini and the medusa container takes care.

**Comment by alokhom** [comment]
i have provided just the bucketname this time and the backup worked. 
The medusa has no support in values.yaml for folder inside a bucket. Usually a folder inside a bucket is searched with a prefix mention but it looks like a `.cassandra` folder is auto created inside a bucket.

**Comment by alokhom** [comment]
@jdonenine I am facing issues with the cassandra backup using google_storage driver.
I only see one pod folder created in the google store instead of 3 pods for 3 racks. 
configuration used in helm values.yaml
```
spec:
  values:
    medusa:
      enabled: true
      multiTenant: true
      storage: google_storage
      bucketName: gcloudsxxxxx
      storageSecret: google-storage-s3-json
```
the google store shows only folders for index and main-cluster-dc1-rack1-sts-0 and no folders for main-cluster-dc1-rack1-sts-1 and main-cluster-dc1-rack1-sts-2. 
logs for medusa operator 
[cassandra-medusa-operator-54fb4b8b9d-x47kq.txt](https://github.com/k8ssandra/k8ssandra/files/8161024/cassandra-medusa-operator-54fb4b8b9d-x47kq.txt)

**Comment by jdonenine** [comment]
Thanks @alokhom I saw the other issue you put in this morning, we'll try to get a look into this and that as soon as we can.

@adejanovski any quick ideas off the top of your head on these or any additional info to gather before we can get a deeper look?  

The other issue is here:  https://github.com/k8ssandra/k8ssandra/issues/1328

**Comment by adejanovski** [comment]
I'll take a close look at both issues.

**Comment by adejanovski** [comment]
Indeed, for the current issue, the bucket name should be provided without any subfolder. Setting it multi tenancy to true will use the cluster name as subfolder in the bucket.
This is still the default behavior in k8ssandra-operator, but you can now specify a custom prefix instead of the cluster name: https://github.com/k8ssandra/k8ssandra-operator/blob/main/apis/medusa/v1alpha1/medusa_types.go#L43-L46
