### ISSUE TITLE
K8SSAND-1288 ⁃ Hung jobs, reaper is trying to connect to old IPs that don't exists

### ISSUE THREAD

**Issue by mikekuzak** [k8ssandra/k8ssandra#1314]
I have the same issue: 
k8ssandra Helm 1.4.1 (reaper version 3.0.0, now 3.1.1) 
K8s v1.20
cassandra 3.11.10

```
cassandra:
  version: "3.11.10"
  allowMultipleNodesPerWorker: false
  cassandraLibDirVolume:
    storageClass: local-path
    size: 120Gi
  heap:
   size: 6G
   newGenSize: 6G
  resources:
    limits:
      cpu: 4000m
      memory: 10Gi
  datacenters:
  - name: dc1
    size: 3
    racks:
    - name: default
  enabled: true
  replicas: 2
  heapMB: 256
  cassandraYamlConfigMap: cassandra-config
  cpuReqMillicores: 200
  cpuLimMillicores: 2000
  ingress:
    enabled: false

reaper:
  image:
     tag: 3.1.1
  enabled: true
  autoschedule: true
  ingress:
    enabled: false
```

Some repairs are working, but when the nodes get bounced it looks like it tries to connect to wrong IPs which don't exists anymore. 

```
ERROR  [2022-02-21 18:24:35,489] [k8ssandra:6e1a4470-884c-11ec-8b2e-4be0f858f67a] i.c.j.JmxConnectionFactory - Failed creating a new JMX connection to 10.42.5.150:7199
java.lang.RuntimeException: io.cassandrareaper.ReaperException: Failure when establishing JMX connection to 10.42.5.150:7199
	at io.cassandrareaper.jmx.JmxConnectionFactory$JmxConnectionProvider.apply(JmxConnectionFactory.java:250)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.cassandrareaper.jmx.JmxConnectionFactory.connectImpl(JmxConnectionFactory.java:111)
	at io.cassandrareaper.jmx.JmxConnectionFactory.connectAny(JmxConnectionFactory.java:148)
	at io.cassandrareaper.jmx.ClusterFacade.connectImpl(ClusterFacade.java:888)
	at io.cassandrareaper.jmx.ClusterFacade.connect(ClusterFacade.java:872)
	at io.cassandrareaper.service.RepairRunner.startNextSegment(RepairRunner.java:414)
	at io.cassandrareaper.service.RepairRunner.run(RepairRunner.java:204)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at com.codahale.metrics.InstrumentedScheduledExecutorService$InstrumentedRunnable.run(InstrumentedScheduledExecutorService.java:241)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.cassandrareaper.ReaperException: Failure when establishing JMX connection to 10.42.5.150:7199
	at io.cassandrareaper.jmx.JmxProxyImpl.connect(JmxProxyImpl.java:284)
	at io.cassandrareaper.jmx.JmxProxyImpl.connect(JmxProxyImpl.java:178)
	at io.cassandrareaper.jmx.JmxConnectionFactory$JmxConnectionProvider.apply(JmxConnectionFactory.java:246)
	... 19 common frames omitted
Caused by: java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at io.cassandrareaper.jmx.JmxProxyImpl.connectWithTimeout(JmxProxyImpl.java:302)
	at io.cassandrareaper.jmx.JmxProxyImpl.connect(JmxProxyImpl.java:240)
	... 21 common frames omitted
INFO   [2022-02-21 18:24:35,489] [k8ssandra:6e1a4470-884c-11ec-8b2e-4be0f858f67a] i.c.j.JmxConnectionFactory - Unreachable host:
io.cassandrareaper.ReaperException: Failure when establishing JMX connection to 10.42.5.150:7199
	at io.cassandrareaper.jmx.JmxProxyImpl.connect(JmxProxyImpl.java:284)
	at io.cassandrareaper.jmx.JmxProxyImpl.connect(JmxProxyImpl.java:178)
	at io.cassandrareaper.jmx.JmxConnectionFactory$JmxConnectionProvider.apply(JmxConnectionFactory.java:246)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.cassandrareaper.jmx.JmxConnectionFactory.connectImpl(JmxConnectionFactory.java:111)
	at io.cassandrareaper.jmx.JmxConnectionFactory.connectAny(JmxConnectionFactory.java:148)
	at io.cassandrareaper.jmx.ClusterFacade.connectImpl(ClusterFacade.java:888)
	at io.cassandrareaper.jmx.ClusterFacade.connect(ClusterFacade.java:872)
	at io.cassandrareaper.service.RepairRunner.startNextSegment(RepairRunner.java:414)
	at io.cassandrareaper.service.RepairRunner.run(RepairRunner.java:204)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at com.codahale.metrics.InstrumentedScheduledExecutorService$InstrumentedRunnable.run(InstrumentedScheduledExecutorService.java:241)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at io.cassandrareaper.jmx.JmxProxyImpl.connectWithTimeout(JmxProxyImpl.java:302)
	at io.cassandrareaper.jmx.JmxProxyImpl.connect(JmxProxyImpl.java:240)
	... 21 common frames omitted
INFO   [2022-02-21 18:24:39,556] [ReaperApplication-scheduler] i.c.s.RepairManager - Restarting run id fc29ed90-88e4-11ec-8b2e-4be0f858f67a that has no runner
INFO   [2022-02-21 18:24:39,556] [ReaperApplication-scheduler] i.c.s.RepairManager - Starting a run with id #fc29ed90-88e4-11ec-8b2e-4be0f858f67a with current state 'RUNNING'
INFO   [2022-02-21 18:24:39,556] [ReaperApplication-scheduler] i.c.s.RepairManager - re-trigger a running run after restart, with id fc29ed90-88e4-11ec-8b2e-4be0f858f67a
INFO   [2022-02-21 18:24:39,557] [ReaperApplication-scheduler] i.c.s.RepairManager - Restarting run id b04b22e0-8d35-11ec-9601-bddbd9bae48a that has no runner
INFO   [2022-02-21 18:24:39,557] [ReaperApplication-scheduler] i.c.s.RepairManager - Starting a run with id #b04b22e0-8d35-11ec-9601-bddbd9bae48a with current state 'RUNNING'
INFO   [2022-02-21 18:24:39,557] [ReaperApplication-scheduler] i.c.s.RepairManager - re-trigger a running run after restart, with id b04b22e0-8d35-11ec-9601-bddbd9bae48a
INFO   [2022-02-21 18:24:39,559] [ReaperApplication-scheduler] i.c.s.RepairManager - Restarting run id dde66ef0-933c-11ec-a2b2-97376fcd6419 that has no runner
INFO   [2022-02-21 18:24:39,559] [ReaperApplication-scheduler] i.c.s.RepairManager - Starting a run with id #dde66ef0-933c-11ec-a2b2-97376fcd6419 with current state 'RUNNING'
INFO   [2022-02-21 18:24:39,559] [ReaperApplication-scheduler] i.c.s.RepairManager - re-trigger a running run after restart, with id dde66ef0-933c-11ec-a2b2-97376fcd6419
INFO   [2022-02-21 18:24:39,560] [ReaperApplication-scheduler] i.c.s.RepairManager - Restarting run id 658b2980-8d03-11ec-9601-bddbd9bae48a that has no runner
INFO   [2022-02-21 18:24:39,560] [ReaperApplication-scheduler] i.c.s.RepairManager - Starting a run with id #658b2980-8d03-11ec-9601-bddbd9bae48a with current state 'RUNNING'
INFO   [2022-02-21 18:24:39,560] [ReaperApplication-scheduler] i.c.s.RepairManager - re-trigger a running run after restart, with id 658b2980-8d03-11ec-9601-bddbd9bae48a
INFO   [2022-02-21 18:24:39,560] [ReaperApplication-scheduler] i.c.s.RepairManager - Restarting run id 6e05f920-884c-11ec-8b2e-4be0f858f67a that has no runner
INFO   [2022-02-21 18:24:39,560] [ReaperApplication-scheduler] i.c.s.RepairManager - Starting a run with id #6e05f920-884c-11ec-8b2e-4be0f858f67a with current state 'RUNNING'
INFO   [2022-02-21 18:24:39,560] [ReaperApplication-scheduler] i.c.s.RepairManager - re-trigger a running run after restart, with id 6e05f920-884c-11ec-8b2e-4be0f858f67a
INFO   [2022-02-21 18:24:39,561] [ReaperApplication-scheduler] i.c.s.RepairManager - Restarting run id 003da630-8c08-11ec-8c89-b34e1ea20948 that has no runner
INFO   [2022-02-21 18:24:39,561] [ReaperApplication-scheduler] i.c.s.RepairManager - Starting a run with id #003da630-8c08-11ec-8c89-b34e1ea20948 with current state 'RUNNING'
INFO   [2022-02-21 18:24:39,561] [ReaperApplication-scheduler] i.c.s.RepairManager - re-trigger a running run after restart, with id 003da630-8c08-11ec-8c89-b34e1ea20948
INFO   [2022-02-21 18:24:49,626] [ReaperApplication-scheduler] i.c.s.RepairManager - Restarting run id fc29ed90-88e4-11ec-8b2e-4be0f858f67a that has no runner
INFO   [2022-02-21 18:24:49,627] [ReaperApplication-scheduler] i.c.s.RepairManager - Starting a run with id #fc29ed90-88e4-11ec-8b2e-4be0f858f67a with current state 'RUNNING'
INFO   [2022-02-21 18:24:49,627] [ReaperApplication-scheduler] i.c.s.RepairManager - re-trigger a running run after restart, with id fc29ed90-88e4-11ec-8b2e-4be0f858f67a
INFO   [2022-02-21 18:24:49,628] [ReaperApplication-scheduler] i.c.s.RepairManager - Restarting run id b04b22e0-8d35-11ec-9601-bddbd9bae48a that has no runner
INFO   [2022-02-21 18:24:49,628] [ReaperApplication-scheduler] i.c.s.RepairManager - Starting a run with id #b04b22e0-8d35-11ec-9601-bddbd9bae48a with current state 'RUNNING'
INFO   [2022-02-21 18:24:49,628] [ReaperApplication-scheduler] i.c.s.RepairManager - re-trigger a running run after restart, with id b04b22e0-8d35-11ec-9601-bddbd9bae48a
INFO   [2022-02-21 18:24:49,629] [ReaperApplication-scheduler] i.c.s.RepairManager - Restarting run id dde66ef0-933c-11ec-a2b2-97376fcd6419 that has no runner
INFO   [2022-02-21 18:24:49,629] [ReaperApplication-scheduler] i.c.s.RepairManager - Starting a run with id #dde66ef0-933c-11ec-a2b2-97376fcd6419 with current state 'RUNNING'
INFO   [2022-02-21 18:24:49,629] [ReaperApplication-scheduler] i.c.s.RepairManager - re-trigger a running run after restart, with id dde66ef0-933c-11ec-a2b2-97376fcd6419
INFO   [2022-02-21 18:24:49,631] [ReaperApplication-scheduler] i.c.s.RepairManager - Restarting run id 658b2980-8d03-11ec-9601-bddbd9bae48a that has no runner
INFO   [2022-02-21 18:24:49,631] [ReaperApplication-scheduler] i.c.s.RepairManager - Starting a run with id #658b2980-8d03-11ec-9601-bddbd9bae48a with current state 'RUNNING'
INFO   [2022-02-21 18:24:49,631] [ReaperApplication-scheduler] i.c.s.RepairManager - re-trigger a running run after restart, with id 658b2980-8d03-11ec-9601-bddbd9bae48a
INFO   [2022-02-21 18:24:49,632] [ReaperApplication-scheduler] i.c.s.RepairManager - Restarting run id 6e05f920-884c-11ec-8b2e-4be0f858f67a that has no runner
INFO   [2022-02-21 18:24:49,632] [ReaperApplication-scheduler] i.c.s.RepairManager - Starting a run with id #6e05f920-884c-11ec-8b2e-4be0f858f67a with current state 'RUNNING'
INFO   [2022-02-21 18:24:49,632] [ReaperApplication-scheduler] i.c.s.RepairManager - re-trigger a running run after restart, with id 6e05f920-884c-11ec-8b2e-4be0f858f67a
INFO   [2022-02-21 18:24:49,633] [ReaperApplication-scheduler] i.c.s.RepairManager - Restarting run id 003da630-8c08-11ec-8c89-b34e1ea20948 that has no runner
INFO   [2022-02-21 18:24:49,633] [ReaperApplication-scheduler] i.c.s.RepairManager - Starting a run with id #003da630-8c08-11ec-8c89-b34e1ea20948 with current state 'RUNNING'
INFO   [2022-02-21 18:24:49,633] [ReaperApplication-scheduler] i.c.s.RepairManager - re-trigger a running run after restart, with id 003da630-8c08-11ec-8c89-b34e1ea20948
```

![image](https://user-images.githubusercontent.com/18675587/155010223-5d8819b4-cb81-4446-9999-6cd4a0b92221.png)

![image](https://user-images.githubusercontent.com/18675587/155010355-806ba9cb-4d36-4876-ab64-dbc53f1c2a0b.png)

and in the UI you can see the jobs being stuck, 

![image](https://user-images.githubusercontent.com/18675587/155010412-30e70421-7cce-4d67-956b-0dbb684ba33d.png)

![image](https://user-images.githubusercontent.com/18675587/155010541-1c0a696c-7945-4f2a-8fc0-4b44b35115a9.png)

_Originally posted by mikekuzak in https://github.com/k8ssandra/k8ssandra/issues/379#issuecomment-1047143918_

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-1288) by [Unito](https://www.unito.io)
┆fixVersions: k8ssandra-v1.5.0
┆friendlyId: K8SSAND-1288
┆priority: Medium

**Comment by mikekuzak** [comment]
Restarting the pod doesn't help. Is there a workaround to clear out the hung jobs and allow new to start correctly ?
