### ISSUE TITLE
K8SSAND-1455 ⁃ medusa backup: minio backup broken / documentation wrong

### ISSUE THREAD

**Issue by discostur** [k8ssandra/k8ssandra#1384]
Hi,

if you deploy k8ssandra with medusa backup enabled via k8ssandra-operator minio is broken due to wrong bucket name variable.

**Helm Values File:**

```
cassandra:
  enabled: true
  version: "4.0.3"
stargate:
  enabled: false
reaper:
  enabled: false
medusa:
  enabled: true
  storage: s3_compatible
  storage_properties:
    host: s3.minio.de
    secure: true
    bucketName: k8ssandra
    storageSecret: medusa-custom-secret
monitoring:
  grafana:
    provision_dashboards: true
  prometheus:
    provision_service_monitors: true
cass-operator:
  enabled: false
reaper-operator:
  enabled: false
kube-prometheus-stack:
  enabled: false
```

This creates a medusa config map like this:

```
data:
  medusa.ini: |-
    [cassandra]
    # The start and stop commands are not applicable in k8s.
    stop_cmd = /etc/init.d/cassandra stop
    start_cmd = /etc/init.d/cassandra start
    check_running = nodetool version
    use_sudo = False

    [storage]
    use_sudo_for_restore = False
    storage_provider = s3_compatible
    bucketName = k8ssandra
    host = s3.minio.de
    secure = true
    storageSecret = medusa-bucket-key
    bucket_name = awstest
    key_file = /etc/medusa-secrets/medusa_s3_credentials
```

Which results in the following error / pod crash loop backoff:

```
MEDUSA_MODE = GRPC
sleeping for 0 sec
Starting Medusa gRPC service
INFO:root:Init service
[2022-04-13 15:06:37,179] INFO: Init service
DEBUG:root:Loading storage_provider: s3_compatible
[2022-04-13 15:06:37,180] DEBUG: Loading storage_provider: s3_compatible
DEBUG:root:Reading credentials from /etc/medusa-secrets/medusa_s3_credentials
[2022-04-13 15:06:37,180] DEBUG: Reading credentials from /etc/medusa-secrets/medusa_s3_credentials
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): s3.minio.de:443
[2022-04-13 15:06:37,184] DEBUG: Starting new HTTPS connection (1): s3.minio.de:443
DEBUG:urllib3.connectionpool:https://s3.minio.de:443 "HEAD /awstest HTTP/1.1" 404 0
[2022-04-13 15:06:37,299] DEBUG: https://s3.minio.de:443 "HEAD /awstest HTTP/1.1" 404 0
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/cassandra/medusa/service/grpc/server.py", line 297, in <module>
    server.serve()
  File "/home/cassandra/medusa/service/grpc/server.py", line 60, in serve
    medusa_pb2_grpc.add_MedusaServicer_to_server(MedusaService(config), self.grpc_server)
  File "/home/cassandra/medusa/service/grpc/server.py", line 99, in __init__
    self.storage = Storage(config=self.config.storage)
  File "/home/cassandra/medusa/storage/__init__.py", line 72, in __init__
    self.storage_driver = self._connect_storage()
  File "/home/cassandra/medusa/storage/__init__.py", line 88, in _connect_storage
    s3_storage = S3BaseStorage(self._config)
  File "/home/cassandra/medusa/storage/abstract_storage.py", line 40, in __init__
    self.bucket = self.driver.get_container(container_name=config.bucket_name)
  File "/home/cassandra/.local/lib/python3.6/site-packages/libcloud/storage/drivers/s3.py", line 360, in get_container
    container_name=container_name)
libcloud.storage.types.ContainerDoesNotExistError: <ContainerDoesNotExistError in <medusa.libcloud.storage.drivers.s3_base_driver.S3BaseStorageDriver object at 0x7f60cfb64550>, container=awstest, value=None>
```

In the configmap, the value `bucketName = k8ssandra` should be changed to `bucket_name = k8ssandra `

* then the pod starts up correctly. 

On top the documentation is wrong: 

https://docs-v2.k8ssandra.io/tasks/backup-restore/

Regarding the documentation the secret should look like this: 

```
apiVersion: v1
kind: Secret
metadata:
 name: medusa-bucket-key
type: Opaque
stringData:
 # Note that this currently has to be set to credentials!
 credentials: |-
...
```

but this is wrong! It must look like this (found over here: https://github.com/k8ssandra/k8ssandra/blob/main/docs/content/en/tasks/backup-restore/minio/_index.md): 

```
apiVersion: v1
kind: Secret
metadata:
 name: medusa-bucket-key
type: Opaque
stringData:
 # Note that this currently has to be set to medusa_s3_credentials!
 medusa_s3_credentials: |-
...
```

So `credentials` should be renamed to `medusa_s3_credentials`. 

Regards,
Kilian

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1455) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1455
┆priority: Medium

**Comment by discostur** [comment]
Think this can be closed as i pointed out in https://github.com/k8ssandra/k8ssandra/issues/1383 i messed up with the documentation and mixed v1 / v2 deployments up a litte bit :/
