### ISSUE TITLE
Medusa deployment failing for cassandra cluster

### ISSUE THREAD

**Issue by abhi93104** [k8ssandra/k8ssandra#142]
Medusa container in cassandra cluster deployment failing due to wrong AWS region.

``` MEDUSA_MODE = GRPC
sleeping for 0 sec
Starting Medusa gRPC service
DEBUG:root:sleeping for 0 sec
[2020-12-22 17:29:19,068] DEBUG: sleeping for 0 sec
INFO:root:Init service
[2020-12-22 17:29:19,071] INFO: Init service
DEBUG:root:Reading AWS credentials from /etc/medusa-secrets/medusa_s3_credentials
[2020-12-22 17:29:19,071] DEBUG: Reading AWS credentials from /etc/medusa-secrets/medusa_s3_credentials
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): s3.amazonaws.com
[2020-12-22 17:29:19,073] DEBUG: Starting new HTTPS connection (1): s3.amazonaws.com
DEBUG:urllib3.connectionpool:https://s3.amazonaws.com:443 "HEAD /k8s-staging HTTP/1.1" 301 0
[2020-12-22 17:29:19,391] DEBUG: https://s3.amazonaws.com:443 "HEAD /k8s-staging HTTP/1.1" 301 0
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/medusa/service/grpc/server.py", line 139, in <module>
    medusa_pb2_grpc.add_MedusaServicer_to_server(MedusaService(config), server)
  File "/app/medusa/service/grpc/server.py", line 30, in __init__
    self.storage = Storage(config=self.config.storage)
  File "/app/medusa/storage/__init__.py", line 64, in __init__
    self.storage_driver = self._connect_storage()
  File "/app/medusa/storage/__init__.py", line 75, in _connect_storage
    s3_storage = S3Storage(self._config)
  File "/app/medusa/storage/abstract_storage.py", line 40, in __init__
    self.bucket = self.driver.get_container(container_name=config.bucket_name)
  File "/usr/local/lib/python3.6/dist-packages/libcloud/storage/drivers/s3.py", line 351, in get_container
    method='HEAD')
  File "/usr/local/lib/python3.6/dist-packages/libcloud/common/base.py", line 648, in request
    response = responseCls(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/libcloud/common/base.py", line 159, in __init__
    message=self.parse_error(),
  File "/usr/local/lib/python3.6/dist-packages/libcloud/storage/drivers/s3.py", line 140, in parse_error
    driver=S3StorageDriver)
libcloud.common.types.LibcloudError: <LibcloudError in <class 'libcloud.storage.drivers.s3.S3StorageDriver'> 'This bucket is located in a different region. Please use the correct driver. Bucket region "us-west-2", used region "us-east-1".'>
```

**Comment by jsanda** [comment]
Hi @abhi93104,

Thanks for creating the ticket. The problem is that the [medusa-config.yaml](https://github.com/k8ssandra/k8ssandra/blob/main/charts/k8ssandra-cluster/templates/medusa-config.yaml) template only checks for the values of `s3` or `gcs` when setting the `storage_provider` property in `medusa.ini`. 

This should be a pretty straight forward fix. Would you be interesting in working on a PR?

**Comment by abhi93104** [comment]
Sure will work on that and raise the PR

**Comment by jsanda** [comment]
Hi @abhi93104 

That is fantastic! Please reach out with any questions here and/or on the K8ssandra mailing lists.

Before we can accept a PR, you will need to sign the CLA at https://cla.datastax.com/.

Thanks

John

**Comment by burmanm** [comment]
This requires changes in the medusa to fix it. Since I'm doing other changes for the S3 support in the medusa, I'll do this at the same time when I update the image in k8ssandra eventually.

**Comment by alokhom** [comment]
I am getting a similar error for gcs connection from cassandra medusa. 
what would be the gcs bucketName  representation if you have a subfolder inside a bucket ?
The below is failing
```
  values:
    medusa:
      enabled: true
      multiTenant: true
      storage: google_storage
      bucketName: "containername/subfolder-name"
      storageSecret: google-storage-s3-json
 ```
 the credentials are correct and i am able to use restic to push files to the sub-folder. 
 But with medusa i get this error.
```
WARNING:root:Forcing use_sudo to False because Kubernetes mode is enabled
WARNING:root:Forcing use_sudo to False because Kubernetes mode is enabled
INFO:root:Init service
[2022-02-21 16:48:30,872] INFO: Init service
DEBUG:root:Loading storage_provider: google_storage
[2022-02-21 16:48:30,872] DEBUG: Loading storage_provider: google_storage
INFO:libcloud.common.google:Failed to read cached auth token from file "/home/cassandra/.google_libcloud_auth.piscadastagingcassandramedusa@piscadaonline.iam.gserviceaccount.com": [Errno 2] No such file or directory: '/home/cassandra/.google_libcloud_auth.piscadastagingcassandramedusa@piscadaonline.iam.gserviceaccount.com'
[2022-02-21 16:48:30,872] INFO: Failed to read cached auth token from file "/home/cassandra/.google_libcloud_auth.piscadastagingcassandramedusa@piscadaonline.iam.gserviceaccount.com": [Errno 2] No such file or directory: '/home/cassandra/.google_libcloud_auth.piscadastagingcassandramedusa@piscadaonline.iam.gserviceaccount.com'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): accounts.google.com:443
[2022-02-21 16:48:30,919] DEBUG: Starting new HTTPS connection (1): accounts.google.com:443
DEBUG:urllib3.connectionpool:https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
[2022-02-21 16:48:30,952] DEBUG: https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): storage.googleapis.com:443
[2022-02-21 16:48:30,958] DEBUG: Starting new HTTPS connection (1): storage.googleapis.com:443
DEBUG:urllib3.connectionpool:https://storage.googleapis.com:443 "HEAD /gcloudstagingpiscadaonline/cassandra HTTP/1.1" 404 0
[2022-02-21 16:48:31,015] DEBUG: https://storage.googleapis.com:443 "HEAD /gcloudstagingpiscadaonline/cassandra HTTP/1.1" 404 0
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/cassandra/medusa/service/grpc/server.py", line 297, in <module>
    server.serve()
  File "/home/cassandra/medusa/service/grpc/server.py", line 60, in serve
    medusa_pb2_grpc.add_MedusaServicer_to_server(MedusaService(config), self.grpc_server)
  File "/home/cassandra/medusa/service/grpc/server.py", line 99, in __init__
    self.storage = Storage(config=self.config.storage)
  File "/home/cassandra/medusa/storage/__init__.py", line 72, in __init__
    self.storage_driver = self._connect_storage()
  File "/home/cassandra/medusa/storage/__init__.py", line 78, in _connect_storage
    google_storage = GoogleStorage(self._config)
  File "/home/cassandra/medusa/storage/abstract_storage.py", line 40, in __init__
    self.bucket = self.driver.get_container(container_name=config.bucket_name)
  File "/home/cassandra/.local/lib/python3.6/site-packages/libcloud/storage/drivers/s3.py", line 360, in get_container
    container_name=container_name)
libcloud.storage.types.ContainerDoesNotExistError: <ContainerDoesNotExistError in <libcloud.storage.drivers.google_storage.GoogleStorageDriver object at 0x7f5123d01208>, container=gcloudstagingpiscadaonline/cassandra, value=None>
```
