### ISSUE TITLE
reaper-schema-job fails on the main version with default settings

### ISSUE THREAD

**Issue by burmanm** [k8ssandra/k8ssandra#209]
## Bug Report

**Describe the bug**
helm install no longer proceeds succesfully with the default settings.

**To Reproduce**
helm install demo charts/k8ssandra

**Screenshots**
⋊> ~/p/g/d/k8ssandra on main ◦ kubectl logs --namespace cass pod/demo-reaper-k8ssandra-schema-j2rxn                                                                                                     16:10:12
keyspace = reaper_db
contact_points = ['k8ssandra-dc1-service']
replication = {'class': 'NetworkTopologyStrategy', 'dc1': 1}
Traceback (most recent call last):
  File "/app/create_keyspace.py", line 31, in <module>
    session = cluster.connect()
  File "cassandra/cluster.py", line 1654, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 1690, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 1677, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 3373, in cassandra.cluster.ControlConnection.connect
  File "cassandra/cluster.py", line 3418, in cassandra.cluster.ControlConnection._reconnect_internal
cassandra.cluster.NoHostAvailable: ('Unable to connect to any servers', {'10.244.0.16:9042': AuthenticationFailed('Failed to authenticate to 10.244.0.16:9042: Error from server: code=0100 [Bad credentials] message="Provided username cassandra and/or password are incorrect"')})
⋊> ~/p/g/d/k8ssandra on main ◦

**Comment by jsanda** [comment]
This should be fixed by #153.
