### ISSUE TITLE
backups fail silently

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#256]
## Bug Report

**Describe the bug**
I have been testing out backup/restore as part of the work to upgrade some components. I failed to make a config change that is necessary with the upgrade. This resulted in backups failing. I was debugging for some time before realizing that the backup failed.

medusa-operator did not log anything to indicate that the backup failed. Here is what it logged:

```
2021-01-27T03:08:52.284Z	INFO	controllers.CassandraBackup	starting backup	{"CassandraPod": "test-dc1-default-sts-1"}
2021-01-27T03:08:52.284Z	INFO	controllers.CassandraBackup	starting backup	{"CassandraPod": "test-dc1-default-sts-2"}
2021-01-27T03:08:52.284Z	INFO	controllers.CassandraBackup	starting backup	{"CassandraPod": "test-dc1-default-sts-0"}
2021-01-27T03:08:52.518Z	DEBUG	controller	Successfully Reconciled	{"reconcilerGroup": "cassandra.k8ssandra.io", "reconcilerKind": "CassandraBackup", "controller": "cassandrabackup", "name": "backup-1", "namespace": "default"}
2021-01-27T03:08:52.518Z	INFO	controllers.CassandraBackup	starting backup	{"CassandraPod": "test-dc1-default-sts-0"}
2021-01-27T03:08:52.519Z	INFO	controllers.CassandraBackup	starting backup	{"CassandraPod": "test-dc1-default-sts-1"}
2021-01-27T03:08:52.519Z	INFO	controllers.CassandraBackup	starting backup	{"CassandraPod": "test-dc1-default-sts-2"}
2021-01-27T03:08:56.801Z	INFO	controllers.CassandraBackup	finished backup	{"CassandraPod": "test-dc1-default-sts-0"}
2021-01-27T03:08:56.805Z	INFO	controllers.CassandraBackup	finished backup	{"CassandraPod": "test-dc1-default-sts-2"}
2021-01-27T03:08:56.841Z	INFO	controllers.CassandraBackup	finished backup	{"CassandraPod": "test-dc1-default-sts-0"}
2021-01-27T03:08:56.928Z	INFO	controllers.CassandraBackup	finished backup	{"CassandraPod": "test-dc1-default-sts-1"}
2021-01-27T03:08:56.942Z	INFO	controllers.CassandraBackup	finished backup	{"CassandraPod": "test-dc1-default-sts-1"}
2021-01-27T03:08:57.018Z	INFO	controllers.CassandraBackup	finished backup	{"CassandraPod": "test-dc1-default-sts-2"}
2021-01-27T03:08:57.019Z	INFO	controllers.CassandraBackup	backup complete
2021-01-27T03:08:57.074Z	DEBUG	controller	Successfully Reconciled	{"reconcilerGroup": "cassandra.k8ssandra.io", "reconcilerKind": "CassandraBackup", "controller": "cassandrabackup", "name": "backup-1", "namespace": "default"}
2021-01-27T03:08:57.074Z	INFO	controllers.CassandraBackup	backup complete
```

The status of the CassandraBackup object give no indication of failure. Here is what it looked like:

```yaml
status:
  ...
  finishTime: "2021-01-27T03:08:57Z"
  finished:
  - test-dc1-default-sts-0
  - test-dc1-default-sts-1
  - test-dc1-default-sts-2
  startTime: "2021-01-27T03:08:52Z"
```

**To Reproduce**
1. Follow the prerequisite steps to set up an S3 or GCS bucket 
2. Create a secret with the S3/GCS credentials
3. Edit the `k8ssandra/templates/medusa-config.yaml` template. Add `enabled = 0` in the `kubernetes` section. This will cause Medusa to try and use `nodetool` which is not available.
4. Install k8ssandra from git (main branch) with backup/restore enabled

`$ helm install test ./k8ssandra -f backup-restore-values.yaml`

where backup-restore-values.yaml looks something like this:

```yaml
cassandra:
  clusterName: test
  version: "3.11.7"
  auth:
    enabled: false
  datacenters:
  - name: dc1
    size: 3
backupRestore:
  medusa:
    enabled: true
    bucketName: k8ssandra
    bucketSecret: medusa-bucket-key
    multiTenant: false
    storage: s3
```

5. Wait for the CassandraDatacenter to become ready
6. Create a backup

`$ helm install backup-test ./backup -f backup-values.yaml`

where backup-values.yaml looks something like this:

```yaml
name: backup-1
cassandraDatacenter:
  name: dc1
```
7. Check the medusa logs with `kubectl logs test-dc1-default-sts-0 -c medusa` and you will find a stack trace similar to this:

```
[2021-01-27 03:08:56,835] INFO: Starting backup
INFO:root:Creating snapshot
[2021-01-27 03:08:56,835] INFO: Creating snapshot
DEBUG:root:Executing: nodetool snapshot -t medusa-backup-1
[2021-01-27 03:08:56,836] DEBUG: Executing: nodetool snapshot -t medusa-backup-1
ERROR:root:backup failed
Traceback (most recent call last):
  File "/app/medusa/service/grpc/server.py", line 51, in Backup
    medusa.backup_node.main(self.config, request.name, None, "differential")
  File "/app/medusa/backup_node.py", line 223, in main
    config
  File "/app/medusa/utils.py", line 35, in handle_exception
    raise exception
  File "/app/medusa/backup_node.py", line 207, in main
    cassandra, node_backup, storage, differential_mode, config, backup_name)
  File "/app/medusa/backup_node.py", line 254, in do_backup
    with cassandra.create_snapshot(backup_name) as snapshot:
  File "/app/medusa/cassandra_utils.py", line 440, in create_snapshot
    subprocess.check_call(cmd, stdout=subprocess.DEVNULL, universal_newlines=True)
  File "/usr/lib/python3.6/subprocess.py", line 306, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'nodetool': 'nodetool'
[2021-01-27 03:08:56,840] ERROR: backup failed
Traceback (most recent call last):
  File "/app/medusa/service/grpc/server.py", line 51, in Backup
    medusa.backup_node.main(self.config, request.name, None, "differential")
  File "/app/medusa/backup_node.py", line 223, in main
    config
  File "/app/medusa/utils.py", line 35, in handle_exception
    raise exception
  File "/app/medusa/backup_node.py", line 207, in main
    cassandra, node_backup, storage, differential_mode, config, backup_name)
  File "/app/medusa/backup_node.py", line 254, in do_backup
    with cassandra.create_snapshot(backup_name) as snapshot:
  File "/app/medusa/cassandra_utils.py", line 440, in create_snapshot
    subprocess.check_call(cmd, stdout=subprocess.DEVNULL, universal_newlines=True)
  File "/usr/lib/python3.6/subprocess.py", line 306, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'nodetool': 'nodetool'
```

**Expected behavior**
A backup can fail for any number of reasons. The status of the CassandraBackup should report the success/failure of the C* nodes involved. This is imperative for users.

It would also be good to see improved logging in medusa-operator.

* Helm charts version info
0.33.0

**Comment by burmanm** [comment]
I wonder if this is related to the gRPC service. The medusa-operator would return an error if the gRPC service returns a failure:

```go
				r.Log.Error(err, "backup failed", "CassandraPod", pod.Name)
```

Potentially it does not catch this nodetool issue..

**Comment by burmanm** [comment]
Yeah, this is in the grpc server of Cassandra-medusa, Backup method in server. py is not setting the correct context if an Exception is encountered.

**Comment by jsanda** [comment]
Nice find! I will build an image off of your PR and test.

**Comment by jsanda** [comment]
I tested with the image in https://github.com/thelastpickle/cassandra-medusa/pull/265 and the changes look good. Here are the logs from my medusa-operator pod:

```
2021-01-27T17:54:04.761Z	DEBUG	controller	Successfully Reconciled	{"reconcilerGroup": "cassandra.k8ssandra.io", "reconcilerKind": "CassandraBackup", "controller": "cassandrabackup", "name": "backup-1", "namespace": "default"}
2021-01-27T17:54:04.761Z	INFO	controllers.CassandraBackup	starting backup	{"CassandraPod": "test-dc1-default-sts-1"}
2021-01-27T17:54:04.761Z	INFO	controllers.CassandraBackup	starting backup	{"CassandraPod": "test-dc1-default-sts-0"}
2021-01-27T17:54:04.761Z	INFO	controllers.CassandraBackup	starting backup	{"CassandraPod": "test-dc1-default-sts-2"}
2021-01-27T17:54:09.247Z	ERROR	controllers.CassandraBackup	backup failed	{"CassandraPod": "test-dc1-default-sts-1", "error": "rpc error: code = Internal desc = failed to create backups: [Errno 2] No such file or directory: 'nodetool': 'nodetool'"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
github.com/k8ssandra/medusa-operator/controllers.(*CassandraBackupReconciler).Reconcile.func1
	/workspace/controllers/cassandrabackup_controller.go:142
2021-01-27T17:54:09.359Z	ERROR	controllers.CassandraBackup	backup failed	{"CassandraPod": "test-dc1-default-sts-2", "error": "rpc error: code = Internal desc = failed to create backups: [Errno 2] No such file or directory: 'nodetool': 'nodetool'"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
github.com/k8ssandra/medusa-operator/controllers.(*CassandraBackupReconciler).Reconcile.func1
	/workspace/controllers/cassandrabackup_controller.go:142
2021-01-27T17:54:09.616Z	ERROR	controllers.CassandraBackup	backup failed	{"CassandraPod": "test-dc1-default-sts-0", "error": "rpc error: code = Internal desc = failed to create backups: [Errno 2] No such file or directory: 'nodetool': 'nodetool'"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
github.com/k8ssandra/medusa-operator/controllers.(*CassandraBackupReconciler).Reconcile.func1
	/workspace/controllers/cassandrabackup_controller.go:142
2021-01-27T17:54:09.631Z	INFO	controllers.CassandraBackup	backup complete
```

And here is the status of my CassandraBackup object:

```yaml
status:
  ...
  failed:
  - test-dc1-default-sts-1
  - test-dc1-default-sts-2
  - test-dc1-default-sts-0
  finishTime: "2021-01-27T17:54:09Z"
  startTime: "2021-01-27T17:54:04Z"
```
We are good to go with this 👍

**Comment by jsanda** [comment]
Closed by https://github.com/thelastpickle/cassandra-medusa/pull/265

**Comment by jsanda** [comment]
I mistakenly closed this issue. We still need to update the Medusa image in the k8ssandra chart. I am submitting a PR with the changes now.
