### ISSUE TITLE
Reaper cannot connect to JMX

### ISSUE THREAD

**Issue by stela-leon** [k8ssandra/k8ssandra#379]
Hi people,

First of all thank you so much for maintaining this project. So far looks cool. 
I do have a problem with the Reaper. 

What I did? 
I set up K8ssandra, enabled the Reaper, remote jmx with auth enabled (tested it 'locally' on cassandra node with nodetool -u/-pw, works just fine), the pod in charge with the reaper has the correct jmx credentials (based on kubernetes dashboard, they're the same as the ones i tested in cassandra). The reaper has connectivity with the cluster, I can see it in the UI. The reaper_db in cassandra gets populated as well. 
The problem pops out when I am trying to run the repair, I get the error:
`INFO   [2021-02-17 17:16:00,087] [k8ssandra: i.c.j.JmxConnectionFactory - Unreachable host: Failure when establishing JMX connection to 192.168.34.85:7199: java.lang.SecurityException: Authentication failed! Invalid username or password 
WARN   [2021-02-17 17:16:00,087] [ i.c.s.SegmentRunner - Failed to connect to a coordinator node for segment 
io.cassandrareaper.ReaperException: no host could be reached through JMX 	at io.cassandrareaper.jmx.JmxConnectionFactory.connectAny(JmxConnectionFactory.java:147)
	at io.cassandrareaper.jmx.ClusterFacade.connectImpl(ClusterFacade.java:809)
	at io.cassandrareaper.jmx.ClusterFacade.connect(ClusterFacade.java:793)
	at io.cassandrareaper.service.SegmentRunner.runRepair(SegmentRunner.java:269)
	at io.cassandrareaper.service.SegmentRunner.run(SegmentRunner.java:181)
....`

While I will continue bashing my head against the wall... Any hints are highly appreciated...

**Comment by jsanda** [comment]
Hi @stela-leon 

Can you please provide the following info:

* The k8ssandra chart version you installed
* Any file you specified with `helm install -f`
* Any properties you set on the command line with `helm install --set`
* The Kubernetes version

**Comment by StelaLeon** [comment]
Hey,

I am using k8ssandra 0.17.1(app version 3.11.7), kubernetes: v1.18.9-eks-d1db3c (eks managed). 
Meanwhile I fixed it: only one of my cassandra nodes had different credentials than the rest, hence it was blocking the repair. 
I can see that the password and username are generated randomly, so I am guessing one of the cass pods got stuck in an intermediate state while the rest recorded the new generated credentials.  

Thanks for the help

**Comment by jsanda** [comment]
There have been a lot of changes since 0.17.1. Here are the latest available chart versions:

```
$ helm search repo k8ssandra
NAME                       	CHART VERSION	APP VERSION	DESCRIPTION
k8ssandra/k8ssandra        	0.52.0       	3.11.10    	Provisions and configures an instance of the en...
k8ssandra/k8ssandra-cluster	0.23.0       	3.11.7     	Configures and creates a k8ssandra cluster
k8ssandra/k8ssandra-common 	0.28.0       	           	Helper library containing functions used by man...
k8ssandra/backup           	0.26.0       	           	Creates a CassandraBackup custom resource insta...
k8ssandra/cass-operator    	0.28.0       	1.5.0      	Kubernetes operator which handles the provision...
k8ssandra/medusa-operator  	0.27.0       	0.1.0      	Installs and configures the Medusa Operator for...
k8ssandra/reaper-operator  	0.29.0       	0.1.0      	Configures and installs the Reaper Operator for...
k8ssandra/restore          	0.27.0       	           	Creates a CassandraRestore custom resource inst..
```
Can you try again with the latest version?

**Comment by an-tex** [comment]
I have the same issue after a fresh install with the latest 1.4.1. It seems the `cassandra-reaper-jmx` secret is being updated at some point after the reaper pods have already started (as it's being shown as OutOfSync in argocd), restarting the pod manually makes the error messages go away (as it's then using the updated secret)

**Comment by mikekuzak** [comment]
I have the same issue: 
k8ssandra Helm 1.4.1 (reaper version 3.0.0, now 3.1.1) 
K8s v1.20
cassandra 3.11.10

```
cassandra:
  version: "3.11.10"
  allowMultipleNodesPerWorker: false
  cassandraLibDirVolume:
    storageClass: local-path
    size: 120Gi
  heap:
   size: 6G
   newGenSize: 6G
  resources:
    limits:
      cpu: 4000m
      memory: 10Gi
  datacenters:
  - name: dc1
    size: 3
    racks:
    - name: default
  enabled: true
  replicas: 2
  heapMB: 256
  cassandraYamlConfigMap: cassandra-config
  cpuReqMillicores: 200
  cpuLimMillicores: 2000
  ingress:
    enabled: false

reaper:
  image:
     tag: 3.1.1
  enabled: true
  autoschedule: true
  ingress:
    enabled: false
```

Some repairs are working, but when the nodes get bounced it looks like it tries to connect to wrong IPs which don't exists anymore. 

```
ERROR  [2022-02-21 18:24:35,489] [k8ssandra:6e1a4470-884c-11ec-8b2e-4be0f858f67a] i.c.j.JmxConnectionFactory - Failed creating a new JMX connection to 10.42.5.150:7199
java.lang.RuntimeException: io.cassandrareaper.ReaperException: Failure when establishing JMX connection to 10.42.5.150:7199
	at io.cassandrareaper.jmx.JmxConnectionFactory$JmxConnectionProvider.apply(JmxConnectionFactory.java:250)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.cassandrareaper.jmx.JmxConnectionFactory.connectImpl(JmxConnectionFactory.java:111)
	at io.cassandrareaper.jmx.JmxConnectionFactory.connectAny(JmxConnectionFactory.java:148)
	at io.cassandrareaper.jmx.ClusterFacade.connectImpl(ClusterFacade.java:888)
	at io.cassandrareaper.jmx.ClusterFacade.connect(ClusterFacade.java:872)
	at io.cassandrareaper.service.RepairRunner.startNextSegment(RepairRunner.java:414)
	at io.cassandrareaper.service.RepairRunner.run(RepairRunner.java:204)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at com.codahale.metrics.InstrumentedScheduledExecutorService$InstrumentedRunnable.run(InstrumentedScheduledExecutorService.java:241)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.cassandrareaper.ReaperException: Failure when establishing JMX connection to 10.42.5.150:7199
	at io.cassandrareaper.jmx.JmxProxyImpl.connect(JmxProxyImpl.java:284)
	at io.cassandrareaper.jmx.JmxProxyImpl.connect(JmxProxyImpl.java:178)
	at io.cassandrareaper.jmx.JmxConnectionFactory$JmxConnectionProvider.apply(JmxConnectionFactory.java:246)
	... 19 common frames omitted
Caused by: java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at io.cassandrareaper.jmx.JmxProxyImpl.connectWithTimeout(JmxProxyImpl.java:302)
	at io.cassandrareaper.jmx.JmxProxyImpl.connect(JmxProxyImpl.java:240)
	... 21 common frames omitted
INFO   [2022-02-21 18:24:35,489] [k8ssandra:6e1a4470-884c-11ec-8b2e-4be0f858f67a] i.c.j.JmxConnectionFactory - Unreachable host:
io.cassandrareaper.ReaperException: Failure when establishing JMX connection to 10.42.5.150:7199
	at io.cassandrareaper.jmx.JmxProxyImpl.connect(JmxProxyImpl.java:284)
	at io.cassandrareaper.jmx.JmxProxyImpl.connect(JmxProxyImpl.java:178)
	at io.cassandrareaper.jmx.JmxConnectionFactory$JmxConnectionProvider.apply(JmxConnectionFactory.java:246)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.cassandrareaper.jmx.JmxConnectionFactory.connectImpl(JmxConnectionFactory.java:111)
	at io.cassandrareaper.jmx.JmxConnectionFactory.connectAny(JmxConnectionFactory.java:148)
	at io.cassandrareaper.jmx.ClusterFacade.connectImpl(ClusterFacade.java:888)
	at io.cassandrareaper.jmx.ClusterFacade.connect(ClusterFacade.java:872)
	at io.cassandrareaper.service.RepairRunner.startNextSegment(RepairRunner.java:414)
	at io.cassandrareaper.service.RepairRunner.run(RepairRunner.java:204)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at com.codahale.metrics.InstrumentedScheduledExecutorService$InstrumentedRunnable.run(InstrumentedScheduledExecutorService.java:241)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at io.cassandrareaper.jmx.JmxProxyImpl.connectWithTimeout(JmxProxyImpl.java:302)
	at io.cassandrareaper.jmx.JmxProxyImpl.connect(JmxProxyImpl.java:240)
	... 21 common frames omitted
INFO   [2022-02-21 18:24:39,556] [ReaperApplication-scheduler] i.c.s.RepairManager - Restarting run id fc29ed90-88e4-11ec-8b2e-4be0f858f67a that has no runner
INFO   [2022-02-21 18:24:39,556] [ReaperApplication-scheduler] i.c.s.RepairManager - Starting a run with id #fc29ed90-88e4-11ec-8b2e-4be0f858f67a with current state 'RUNNING'
INFO   [2022-02-21 18:24:39,556] [ReaperApplication-scheduler] i.c.s.RepairManager - re-trigger a running run after restart, with id fc29ed90-88e4-11ec-8b2e-4be0f858f67a
INFO   [2022-02-21 18:24:39,557] [ReaperApplication-scheduler] i.c.s.RepairManager - Restarting run id b04b22e0-8d35-11ec-9601-bddbd9bae48a that has no runner
INFO   [2022-02-21 18:24:39,557] [ReaperApplication-scheduler] i.c.s.RepairManager - Starting a run with id #b04b22e0-8d35-11ec-9601-bddbd9bae48a with current state 'RUNNING'
INFO   [2022-02-21 18:24:39,557] [ReaperApplication-scheduler] i.c.s.RepairManager - re-trigger a running run after restart, with id b04b22e0-8d35-11ec-9601-bddbd9bae48a
INFO   [2022-02-21 18:24:39,559] [ReaperApplication-scheduler] i.c.s.RepairManager - Restarting run id dde66ef0-933c-11ec-a2b2-97376fcd6419 that has no runner
INFO   [2022-02-21 18:24:39,559] [ReaperApplication-scheduler] i.c.s.RepairManager - Starting a run with id #dde66ef0-933c-11ec-a2b2-97376fcd6419 with current state 'RUNNING'
INFO   [2022-02-21 18:24:39,559] [ReaperApplication-scheduler] i.c.s.RepairManager - re-trigger a running run after restart, with id dde66ef0-933c-11ec-a2b2-97376fcd6419
INFO   [2022-02-21 18:24:39,560] [ReaperApplication-scheduler] i.c.s.RepairManager - Restarting run id 658b2980-8d03-11ec-9601-bddbd9bae48a that has no runner
INFO   [2022-02-21 18:24:39,560] [ReaperApplication-scheduler] i.c.s.RepairManager - Starting a run with id #658b2980-8d03-11ec-9601-bddbd9bae48a with current state 'RUNNING'
INFO   [2022-02-21 18:24:39,560] [ReaperApplication-scheduler] i.c.s.RepairManager - re-trigger a running run after restart, with id 658b2980-8d03-11ec-9601-bddbd9bae48a
INFO   [2022-02-21 18:24:39,560] [ReaperApplication-scheduler] i.c.s.RepairManager - Restarting run id 6e05f920-884c-11ec-8b2e-4be0f858f67a that has no runner
INFO   [2022-02-21 18:24:39,560] [ReaperApplication-scheduler] i.c.s.RepairManager - Starting a run with id #6e05f920-884c-11ec-8b2e-4be0f858f67a with current state 'RUNNING'
INFO   [2022-02-21 18:24:39,560] [ReaperApplication-scheduler] i.c.s.RepairManager - re-trigger a running run after restart, with id 6e05f920-884c-11ec-8b2e-4be0f858f67a
INFO   [2022-02-21 18:24:39,561] [ReaperApplication-scheduler] i.c.s.RepairManager - Restarting run id 003da630-8c08-11ec-8c89-b34e1ea20948 that has no runner
INFO   [2022-02-21 18:24:39,561] [ReaperApplication-scheduler] i.c.s.RepairManager - Starting a run with id #003da630-8c08-11ec-8c89-b34e1ea20948 with current state 'RUNNING'
INFO   [2022-02-21 18:24:39,561] [ReaperApplication-scheduler] i.c.s.RepairManager - re-trigger a running run after restart, with id 003da630-8c08-11ec-8c89-b34e1ea20948
INFO   [2022-02-21 18:24:49,626] [ReaperApplication-scheduler] i.c.s.RepairManager - Restarting run id fc29ed90-88e4-11ec-8b2e-4be0f858f67a that has no runner
INFO   [2022-02-21 18:24:49,627] [ReaperApplication-scheduler] i.c.s.RepairManager - Starting a run with id #fc29ed90-88e4-11ec-8b2e-4be0f858f67a with current state 'RUNNING'
INFO   [2022-02-21 18:24:49,627] [ReaperApplication-scheduler] i.c.s.RepairManager - re-trigger a running run after restart, with id fc29ed90-88e4-11ec-8b2e-4be0f858f67a
INFO   [2022-02-21 18:24:49,628] [ReaperApplication-scheduler] i.c.s.RepairManager - Restarting run id b04b22e0-8d35-11ec-9601-bddbd9bae48a that has no runner
INFO   [2022-02-21 18:24:49,628] [ReaperApplication-scheduler] i.c.s.RepairManager - Starting a run with id #b04b22e0-8d35-11ec-9601-bddbd9bae48a with current state 'RUNNING'
INFO   [2022-02-21 18:24:49,628] [ReaperApplication-scheduler] i.c.s.RepairManager - re-trigger a running run after restart, with id b04b22e0-8d35-11ec-9601-bddbd9bae48a
INFO   [2022-02-21 18:24:49,629] [ReaperApplication-scheduler] i.c.s.RepairManager - Restarting run id dde66ef0-933c-11ec-a2b2-97376fcd6419 that has no runner
INFO   [2022-02-21 18:24:49,629] [ReaperApplication-scheduler] i.c.s.RepairManager - Starting a run with id #dde66ef0-933c-11ec-a2b2-97376fcd6419 with current state 'RUNNING'
INFO   [2022-02-21 18:24:49,629] [ReaperApplication-scheduler] i.c.s.RepairManager - re-trigger a running run after restart, with id dde66ef0-933c-11ec-a2b2-97376fcd6419
INFO   [2022-02-21 18:24:49,631] [ReaperApplication-scheduler] i.c.s.RepairManager - Restarting run id 658b2980-8d03-11ec-9601-bddbd9bae48a that has no runner
INFO   [2022-02-21 18:24:49,631] [ReaperApplication-scheduler] i.c.s.RepairManager - Starting a run with id #658b2980-8d03-11ec-9601-bddbd9bae48a with current state 'RUNNING'
INFO   [2022-02-21 18:24:49,631] [ReaperApplication-scheduler] i.c.s.RepairManager - re-trigger a running run after restart, with id 658b2980-8d03-11ec-9601-bddbd9bae48a
INFO   [2022-02-21 18:24:49,632] [ReaperApplication-scheduler] i.c.s.RepairManager - Restarting run id 6e05f920-884c-11ec-8b2e-4be0f858f67a that has no runner
INFO   [2022-02-21 18:24:49,632] [ReaperApplication-scheduler] i.c.s.RepairManager - Starting a run with id #6e05f920-884c-11ec-8b2e-4be0f858f67a with current state 'RUNNING'
INFO   [2022-02-21 18:24:49,632] [ReaperApplication-scheduler] i.c.s.RepairManager - re-trigger a running run after restart, with id 6e05f920-884c-11ec-8b2e-4be0f858f67a
INFO   [2022-02-21 18:24:49,633] [ReaperApplication-scheduler] i.c.s.RepairManager - Restarting run id 003da630-8c08-11ec-8c89-b34e1ea20948 that has no runner
INFO   [2022-02-21 18:24:49,633] [ReaperApplication-scheduler] i.c.s.RepairManager - Starting a run with id #003da630-8c08-11ec-8c89-b34e1ea20948 with current state 'RUNNING'
INFO   [2022-02-21 18:24:49,633] [ReaperApplication-scheduler] i.c.s.RepairManager - re-trigger a running run after restart, with id 003da630-8c08-11ec-8c89-b34e1ea20948
```

![image](https://user-images.githubusercontent.com/18675587/155010223-5d8819b4-cb81-4446-9999-6cd4a0b92221.png)

![image](https://user-images.githubusercontent.com/18675587/155010355-806ba9cb-4d36-4876-ab64-dbc53f1c2a0b.png)

and in the UI you can see the jobs being stuck, 

![image](https://user-images.githubusercontent.com/18675587/155010412-30e70421-7cce-4d67-956b-0dbb684ba33d.png)

![image](https://user-images.githubusercontent.com/18675587/155010541-1c0a696c-7945-4f2a-8fc0-4b44b35115a9.png)

**Comment by jsanda** [comment]
> I have the same issue after a fresh install with the latest 1.4.1. It seems the `cassandra-reaper-jmx` secret is being updated at some point after the reaper pods have already started (as it's being shown as OutOfSync in argocd), restarting the pod manually makes the error messages go away (as it's then using the updated secret)

@an-tex are you updating any credentials? k8ssandra uses the same credentials for both the Cassandra superuser and for JMX. They are separate though and not kept in sync.

**Comment by jsanda** [comment]
>Some repairs are working, but when the nodes get bounced it looks like it tries to connect to wrong IPs which don't exists anymore.

Hey @mikekuzak. Have you changed superuser credentials?

**Comment by mikekuzak** [comment]
> > Some repairs are working, but when the nodes get bounced it looks like it tries to connect to wrong IPs which don't exists anymore.
> 
> Hey @mikekuzak. Have you changed superuser credentials?

nope, just host reboost, after patching.

**Comment by an-tex** [comment]
hi @jsanda , thanks for coming back to me. i've just investigated further and i think i kinda am. "kinda" because i'm using argocd with it's helm controller to install the k8ssandra helm chart. to me it seems the `cassandra-reaper-jmx` is being updated from it's original content of the helm chart (by the operator?), hence argocd recognizes that secret as outofsync. with the next sync (e.g. triggered by an independent commit) the secret is overwritten with it's default helm chart values. so with some bad luck timing we might end up with different secrets. this particular case is not an issue with the k8ssandra itself, even though one might argue it conflicts somewhat with gitops principles.  in my particular case i managed to get around the issue by telling argocd to ignore any differences in this secret (and two other places which are changed from the original helm chart):
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # use a name prefix to make it unique in the cluster https://docs.k8ssandra.io/faqs/#can-i-install-multiple-releases-of-k8ssandra
  name: k8ssandra
spec:
  source:
    repoURL: https://helm.k8ssandra.io/stable
    chart: k8ssandra
    targetRevision: 1.4.1
  # !! important addition starts here
  ignoreDifferences:
    - kind: CassandraDatacenter
      group: cassandra.datastax.com
      jsonPointers:
        # default value false added at runtime but ignored during setup when explicitly defined
        - /spec/allowMultipleNodesPerWorker
    # changed at runtime
    - kind: Secret
      name: cassandra-reaper-jmx
      jsonPointers:
        - /data/password
    - kind: Reaper
      group: reaper.cassandra-reaper.io
      jsonPointers:
        # changed at runtime
        - /spec/serverConfig/autoScheduling
```
i understand this case seems pretty special and i'd understand if you'd be inclined to ignore it :) but it might become a more apparent issue once more people start to use gitops tools like argocd or flux.

**Comment by adejanovski** [comment]
Hi @an-tex,

Argo renders the manifests locally and then applies them, and since there's no operator involved in the password generation but just Helm templates, we can't avoid the behavior you're seeing (This is different than using `helm install` and then `helm upgrade`)
The expectation is that you set all passwords explicitly when deploying to production, especially when using CD tools such as ArgoCD.
Having different secrets being generated each time you deploy the app will break some functionalities, as you've already noticed.

The secrets you'll need to create separately (using SealedSecrets for example) and then reference in the helm values are:

- cassandra.auth.superuser
- stargate.cassandraUser
- medusa.cassandraUser
- reaper.cassandraUser
- reaper.jmx

**Comment by jsanda** [comment]
@mikekuzak 

Am I understanding correctly that restarting the C* pod and it coming up with a different IP address causes your problem?  A

Are you seeing this with earlier versions of K8ssandra and/or Reaper?

**Comment by adejanovski** [comment]
@mikekuzak, the issue you're seeing is different:
Reaper computes the list of replicas for each segment when the repair run is created. If a pod gets restarted during a repair, it will get a new IP and all segments that had the previous IP will fail to be scheduled.
This is a known behavior and we need to figure out a way for gracefully handling this case.
Could you create a separate issue so we can schedule and track the work for it?
Thanks!
