### ISSUE TITLE
Support Stargate with 4.0.0-beta4

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#397]
**Is your feature request related to a problem? Please describe.**
With 4.0.0 support now in place, stargate deployment needs to be updated to accommodate.

Currently, when you deploy stargate with a 4.0.0 cluster stargate will fail to start with errors like:

```
io.stargate.core.activator.ServiceStartException: Unable to start persistence-cassandra-3.11
Detected service startup failure in bundle io.stargate.db.cassandra: io.stargate.core.activator.ServiceStartException: Unable to start persistence-cassandra-3.11
        at io.stargate.core.activator.BaseActivator.startServiceInternal(BaseActivator.java:182)
        at io.stargate.core.activator.BaseActivator.access$900(BaseActivator.java:37)
        at io.stargate.core.activator.BaseActivator$Tracker.startIfAllRegistered(BaseActivator.java:225)
        at io.stargate.core.activator.BaseActivator$Tracker.addingService(BaseActivator.java:201)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:871)
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
        at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:903)
        at org.apache.felix.framework.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:990)
        at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)
        at org.apache.felix.framework.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)
        at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4833)
        at org.apache.felix.framework.Felix.registerService(Felix.java:3804)
        at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:328)
        at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:302)
        at io.stargate.core.activator.BaseActivator.startServiceInternal(BaseActivator.java:175)
        at io.stargate.core.activator.BaseActivator.start(BaseActivator.java:98)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:698)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2402)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984)
        at io.stargate.starter.Starter.start(Starter.java:431)
        at io.stargate.starter.Starter.cli(Starter.java:607)
        at io.stargate.starter.Starter.main(Starter.java:648)
Caused by: java.lang.RuntimeException: A node with address /10.244.2.12 already exists, cancelling join. Use cassandra.replace_address if you want to replace this node.
        at org.apache.cassandra.service.StorageService.checkForEndpointCollision(StorageService.java:597)
        at org.apache.cassandra.service.StorageService.prepareToJoin(StorageService.java:844)
        at org.apache.cassandra.service.StorageService.initServer(StorageService.java:703)
        at org.apache.cassandra.service.StorageService.initServer(StorageService.java:652)
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:397)
        at org.apache.cassandra.service.CassandraDaemon.init(CassandraDaemon.java:521)
        at io.stargate.db.cassandra.impl.CassandraPersistence.initializePersistence(CassandraPersistence.java:171)
        at io.stargate.db.cassandra.impl.CassandraPersistence.initializePersistence(CassandraPersistence.java:94)
        at io.stargate.db.datastore.common.AbstractCassandraPersistence.initialize(AbstractCassandraPersistence.java:106)
        at io.stargate.db.cassandra.CassandraPersistenceActivator.createService(CassandraPersistenceActivator.java:169)
        at io.stargate.core.activator.BaseActivator.createServices(BaseActivator.java:238)
        at io.stargate.core.activator.BaseActivator.startServiceInternal(BaseActivator.java:170)
        ... 25 more
INFO  [main] 2021-02-20 13:38:38,657 BaseActivator.java:173 - Registering core services as com.codahale.metrics.health.HealthCheckRegistry
INFO  [main] 2021-02-20 13:38:38,657 BaseActivator.java:180 - Started core services
Starting bundle io.stargate.cql
INFO  [main] 2021-02-20 13:38:38,953 BaseActivator.java:92 - Starting CQL ...
Starting bundle io.stargate.graphql
INFO  [main] 2021-02-20 13:38:39,393 BaseActivator.java:92 - Starting GraphQL ...
Starting bundle io.stargate.health
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [bundle://ba6c254a-dc3f-4246-b77d-bc04db9f2d36_20.0:82/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [bundle://ba6c254a-dc3f-4246-b77d-bc04db9f2d36_20.0:100/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
INFO  [main] 2021-02-20 13:38:39,792 BaseActivator.java:92 - Starting healthchecker ...
INFO  [main] 2021-02-20 13:38:39,797 HealthCheckerActivator.java:37 - Starting healthchecker....
INFO  [2021-02-20 13:38:43,310] io.dropwizard.server.SimpleServerFactory: Registering jersey handler with root path prefix: /checker/
WARN  [2021-02-20 13:38:43,322] org.eclipse.jetty.server.handler.ContextHandler: i.d.j.MutableServletContextHandler@730bb6{/,null,UNAVAILABLE} contextPath ends with /
INFO  [2021-02-20 13:38:43,326] io.dropwizard.server.SimpleServerFactory: Registering admin handler with root path prefix: /
INFO  [2021-02-20 13:38:43,348] io.dropwizard.server.SimpleServerFactory: Registering jersey handler with root path prefix: /checker/
WARN  [2021-02-20 13:38:43,348] org.eclipse.jetty.server.handler.ContextHandler: i.d.j.MutableServletContextHandler@730bb6{/checker,null,UNAVAILABLE} contextPath ends with /
INFO  [2021-02-20 13:38:43,348] io.dropwizard.server.SimpleServerFactory: Registering admin handler with root path prefix: /
INFO  [2021-02-20 13:38:43,349] io.dropwizard.server.ServerFactory: Starting Server
INFO  [2021-02-20 13:38:43,793] org.eclipse.jetty.setuid.SetUIDListener: Opened Server@34846a1a{HTTP/1.1, (http/1.1)}{0.0.0.0:8084}
INFO  [2021-02-20 13:38:43,800] org.eclipse.jetty.server.Server: jetty-9.4.30.v20200611; built: 2020-06-11T12:34:51.929Z; git: 271836e4c1f4612f12b7bb13ef5a92a927634b0d; jvm 1.8.0_252-b09
INFO  [2021-02-20 13:38:48,520] io.dropwizard.jersey.DropwizardResourceConfig: The following paths were found for the configured resources:

    GET     /liveness (io.stargate.health.CheckerResource)
    GET     /readiness (io.stargate.health.CheckerResource)

INFO  [2021-02-20 13:38:48,539] org.eclipse.jetty.server.handler.ContextHandler: Started i.d.j.MutableServletContextHandler@730bb6{/checker,null,AVAILABLE}
INFO  [2021-02-20 13:38:48,563] io.dropwizard.setup.AdminEnvironment: tasks = 

    POST    /tasks/log-level (io.dropwizard.servlets.tasks.LogConfigurationTask)
    POST    /tasks/gc (io.dropwizard.servlets.tasks.GarbageCollectionTask)

INFO  [2021-02-20 13:38:48,704] org.eclipse.jetty.server.handler.ContextHandler: Started i.d.j.MutableServletContextHandler@d97abe7{/,null,AVAILABLE}
INFO  [2021-02-20 13:38:48,891] org.eclipse.jetty.server.AbstractConnector: Started Server@34846a1a{HTTP/1.1, (http/1.1)}{0.0.0.0:8084}
INFO  [2021-02-20 13:38:48,891] org.eclipse.jetty.server.Server: Started @22772ms
INFO  [2021-02-20 13:38:48,899] io.stargate.health.HealthCheckerActivator: Started healthchecker....
INFO  [main] 2021-02-20 13:38:48,899 BaseActivator.java:180 - Started healthchecker
Starting bundle org.apache.felix.scr
Starting bundle null
Starting bundle null
Starting bundle osgi.cmpn
Starting bundle org.osgi.util.function
Starting bundle org.osgi.util.promise
Starting bundle io.stargate.db
INFO  [main] 2021-02-20 13:38:49,457 BaseActivator.java:92 - Starting DB services ...
Starting bundle io.stargate.db.limiter.global
INFO  [main] 2021-02-20 13:38:49,523 BaseActivator.java:92 - Starting Global Rate Limiting ...
INFO  [main] 2021-02-20 13:38:49,523 BaseActivator.java:180 - Started Global Rate Limiting
Starting bundle io.stargate.web
10.244.1.4 - - [20/Feb/2021:13:38:52 +0000] "GET /metrics HTTP/1.1" 200 1662833 "-" "Prometheus/2.22.1" 2481
INFO  [main] 2021-02-20 13:38:52,390 BaseActivator.java:92 - Starting restapi ...
Terminating due to previous service startup errors.
INFO  [StorageServiceShutdownHook] 2021-02-20 13:38:52,441 HintsService.java:209 - Paused hints dispatch
WARN  [StorageServiceShutdownHook] 2021-02-20 13:38:52,442 Gossiper.java:1655 - No local state, state is in silent shutdown, or node hasn't joined, not announcing shutdown
INFO  [StorageServiceShutdownHook] 2021-02-20 13:38:52,444 MessagingService.java:985 - Waiting for messaging service to quiesce
INFO  [ACCEPT-/10.244.2.12] 2021-02-20 13:38:52,450 MessagingService.java:1346 - MessagingService has terminated the accept() thread
INFO  [2021-02-20 13:38:52,537] org.eclipse.jetty.server.AbstractConnector: Stopped Server@34846a1a{HTTP/1.1, (http/1.1)}{0.0.0.0:8084}
INFO  [2021-02-20 13:38:52,596] org.eclipse.jetty.server.handler.ContextHandler: Stopped i.d.j.MutableServletContextHandler@d97abe7{/,null,UNAVAILABLE}
INFO  [2021-02-20 13:38:52,879] org.eclipse.jetty.server.handler.ContextHandler: Stopped i.d.j.MutableServletContextHandler@730bb6{/checker,null,UNAVAILABLE}
INFO  [StorageServiceShutdownHook] 2021-02-20 13:38:53,767 HintsService.java:209 - Paused hints dispatch
```

**Describe the solution you'd like**
Stargate should function properly when running a 4.0.0 cluster.

**Additional context**
We knew we would need to do this, but adding a specific issue to make sure it doesn't fall through the cracks.

While we do this we should probably bump to the latest Stargate release available as well.

**Comment by jdonenine** [comment]
I can confirm that if you manually for the 4.0 stargate image and the CLUSTER_VERSION to "4.0" things work as expected.

I did that the simplest way possible be exposing the clusterVersion in the values to override:

stargate.yaml
```yaml
            - name: CLUSTER_VERSION
              value: {{ .Values.stargate.clusterVersion | default "3.11" | quote }}
```

and

values.yaml
```yaml
stargate:
  image: stargateio/stargate-4_0:v1.0.8
  clusterVersion: "4.0"
```
