### ISSUE TITLE
K8SSAND-48 ⁃ Gossip errors with Stargate can delay initialization of Cassandra cluster

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#612]
## Bug Report

**Describe the bug**
This was reported earlier by adejanovski. He installed k8ssandra with 2 Cassandra nodes and 1 Stargate node. The Stargate deployment is configure to start Stargate when we have 1 ready Cassandra node.  Alex found the following errors reported in the logs of the second Cassandra node:

```
WARN  [main] 2021-03-31 12:36:38,634 StorageService.java:941 - There are nodes in the cluster with a different schema version than us we did not merged schemas from, our version : (dae4198f-3e84-3b07-a37d-b600d7641dff), outstanding versions -> endpoints : {96d48f4a-c200-381d-8206-7398cc64637e=[/10.244.3.6]}
ERROR [main] 2021-03-31 12:36:38,638 CassandraDaemon.java:803 - Exception encountered during startup
java.lang.RuntimeException: Didn't receive schemas for all known versions within the timeout
	at org.apache.cassandra.service.StorageService.waitForSchema(StorageService.java:947) ~[apache-cassandra-3.11.10.jar:3.11.10]
	at org.apache.cassandra.service.StorageService.joinTokenRing(StorageService.java:987) ~[apache-cassandra-3.11.10.jar:3.11.10]
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:753) ~[apache-cassandra-3.11.10.jar:3.11.10]
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:687) ~[apache-cassandra-3.11.10.jar:3.11.10]
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:395) [apache-cassandra-3.11.10.jar:3.11.10]
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:633) [apache-cassandra-3.11.10.jar:3.11.10]
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:786) [apache-cassandra-3.11.10.jar:3.11.10]
INFO  [StorageServiceShutdownHook] 2021-03-31 12:36:38,642 HintsService.java:209 - Paused hints dispatch
WARN  [StorageServiceShutdownHook] 2021-03-31 12:36:38,643 Gossiper.java:1670 - No local state, state is in silent shutdown, or node hasn't joined, not announcing shutdown
INFO  [StorageServiceShutdownHook] 2021-03-31 12:36:38,644 MessagingService.java:985 - Waiting for messaging service to quiesce
INFO  [ACCEPT-/10.244.1.9] 2021-03-31 12:36:38,644 MessagingService.java:1346 - MessagingService has terminated the accept() thread
INFO  [StorageServiceShutdownHook] 2021-03-31 12:36:38,711 HintsService.java:209 - Paused hints dispatch
```

There is a schema version mismatch between Cassandra and Stargate. Here is what was in the Stargate node's logs:

```
ERROR [main] 2021-03-31 12:36:51,351 CassandraDaemon.java:803 - Exception encountered during startup
java.lang.RuntimeException: A node with address /10.244.1.9 already exists, cancelling join. Use cassandra.replace_address if you want to replace this node.
	at org.apache.cassandra.service.StorageService.checkForEndpointCollision(StorageService.java:632) ~[apache-cassandra-3.11.10.jar:3.11.10]
	at org.apache.cassandra.service.StorageService.prepareToJoin(StorageService.java:880) ~[apache-cassandra-3.11.10.jar:3.11.10]
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:738) ~[apache-cassandra-3.11.10.jar:3.11.10]
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:687) ~[apache-cassandra-3.11.10.jar:3.11.10]
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:395) [apache-cassandra-3.11.10.jar:3.11.10]
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:633) [apache-cassandra-3.11.10.jar:3.11.10]
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:786) [apache-cassandra-3.11.10.jar:3.11.10]
```

The second Cassandra node crashed, the pod eventually restarted, and then it started up.

The safe thing to do is wait to deploy Stargate until all Cassandra nodes are ready.

**To Reproduce**

1. Install k8ssandra with multiple Cassandra nodes and a Stargate node
1. Monitor the Cassandra logs. 
1. The error does not happen consistently so it may require several attempts

**Expected behavior**
Update the init container in the Stargate deployment so that it blocks until the CassandraDatacenter object becomes ready. This should eliminate the gossip confusion which further delay cluster initialization.

**Screenshots**

**Environment (please complete the following information):**

* Helm charts version info
1.0.0
* Helm charts user-supplied values
* Kubernetes version information:
* Kubernetes cluster kind:

**Additional context**

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-48) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-48
┆priority: Medium

**Comment by adejanovski** [comment]
I'd add to that another thing (which we can track separately): Stargate nodes need to bootstrap one by one, just as Cassandra nodes do. Currently if we provision several, they'll all try to join the cluster in parallel.

**Comment by jsanda** [comment]
>Stargate nodes need to bootstrap one by one

If this is the case then we will want to switch to a StatefulSet instead of a Deployment. With a Deployment I do not believe that there is a way to ensure replicas are started serially. That is the default behavior with StatefulSets though.

**Comment by jsanda** [comment]
Closing since this is addressed in k8ssandra-operator.

**Comment by jsanda** [comment]
Closing since this is addressed in k8ssandra-operator.
