### ISSUE TITLE
TestFullStackScenario fails on the Test_Stargate test

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#651]
## Bug Report

**Describe the bug**
The `Test_Stargate` e2e test is consistently failing with an error likes this:

```
=== RUN   TestFullStackScenario/Full_Stack_Test/Test_Stargate
2021/04/08 13:21:37 Writing data to the Stargate document API
TestFullStackScenario/Full_Stack_Test/Test_Stargate 2021-04-08T13:21:37-04:00 client.go:33: Configuring kubectl using config file /Users/johnsanda/.kube/config with context
--- FAIL: TestFullStackScenario (1332.07s)
    --- FAIL: TestFullStackScenario/Full_Stack_Test (1323.79s)
        --- PASS: TestFullStackScenario/Full_Stack_Test/Test_Reaper (31.29s)
        --- PASS: TestFullStackScenario/Full_Stack_Test/Test_Medusa (592.40s)
        --- PASS: TestFullStackScenario/Full_Stack_Test/Test_Prometheus (0.20s)
        --- PASS: TestFullStackScenario/Full_Stack_Test/Test_Grafana (0.08s)
        --- FAIL: TestFullStackScenario/Full_Stack_Test/Test_Stargate (0.88s)
panic: interface conversion: interface {} is nil, not string [recovered]
	panic: interface conversion: interface {} is nil, not string

goroutine 502 [running]:
testing.tRunner.func1.2(0x2315640, 0xc000611680)
	/usr/local/Cellar/go/1.16.2/libexec/src/testing/testing.go:1144 +0x332
testing.tRunner.func1(0xc000583b00)
	/usr/local/Cellar/go/1.16.2/libexec/src/testing/testing.go:1147 +0x4b6
panic(0x2315640, 0xc000611680)
	/usr/local/Cellar/go/1.16.2/libexec/src/runtime/panic.go:965 +0x1b9
github.com/k8ssandra/k8ssandra/tests/integration/steps.GenerateStargateAuthToken(0xc000583b00, 0xc000613f20, 0x19, 0xc000623380, 0x34)
	/Users/johnsanda/Development/k8ssandra/k8ssandra/tests/integration/steps/stargate_steps.go:79 +0x715
github.com/k8ssandra/k8ssandra/tests/integration.testStargate(0xc000583b00, 0xc000613f20, 0x19)
	/Users/johnsanda/Development/k8ssandra/k8ssandra/tests/integration/integration_suite_test.go:317 +0x115
github.com/k8ssandra/k8ssandra/tests/integration.TestFullStackScenario.func1.5(0xc000583b00)
	/Users/johnsanda/Development/k8ssandra/k8ssandra/tests/integration/integration_suite_test.go:104 +0x3d
testing.tRunner(0xc000583b00, 0xc000a4a078)
	/usr/local/Cellar/go/1.16.2/libexec/src/testing/testing.go:1194 +0xef
created by testing.(*T).Run
	/usr/local/Cellar/go/1.16.2/libexec/src/testing/testing.go:1239 +0x2b3
FAIL	github.com/k8ssandra/k8ssandra/tests/integration	1332.566s
FAIL
make: *** [integ-test] Error 1
```

The actual failure happens in this function:

```go
func GenerateStargateAuthToken(t *testing.T, namespace string) string {
	credentials := ExtractUsernamePassword(t, "k8ssandra-superuser", namespace)
	creds := fmt.Sprintf("{\"username\":\"%s\", \"password\":\"%s\"}", credentials.username, credentials.password)
	restClient := resty.New()
	response, err := restClient.R().
		SetHeader("Content-Type", "application/json").
		SetBody(creds).
		Post("http://stargate.127.0.0.1.nip.io:8081/v1/auth")
	g(t).Expect(err).To(BeNil(), "Failed connecting to Stargate")
	stargateResponse := response.Body()
	var genericJson map[string]interface{}
	json.Unmarshal(stargateResponse, &genericJson)
	return genericJson["authToken"].(string)
}
```
The `json.Unmarshal` call isn't checking for an error, but there is another underlying issue. Executing the http request manually reveals the problem:

```
 $ curl -X POST http://stargate.127.0.0.1.nip.io:8081/v1/auth -H 'Content-Type: application/json' --data-raw '{"username": "k8ssandra-superuser", "password": "iXXU3vwVPrkWx5zSpDgB"}'

{"description":"Failed to create token: org.apache.cassandra.stargate.exceptions.UnavailableException: Cannot achieve consistency level ONE"}
```
We are running into #411. The Cassandra cluster is restarted in the backup/restore test which runs before the Stargate test. 

Until Stargate has support to dynamically reload seeds, I am going to update the test to restart Stargate to work around the issue. I will incorporate the changes into #641.

**To Reproduce**
1. Run `make GO_FLAGS=-v CLUSTER_CLEANUP=never kind-integ-test`
2. Verify that `Test_Stargate` fails with an error similar to what I posted above
3. Restart Stargate by deleting the Stargate pod
4. Wait for the new Stargate pod to reach the ready state.
5. Run the curl command I posted above (using your superuser creds)

**Expected behavior**
The test should pass.

**Screenshots**

**Environment (please complete the following information):**

* Helm charts version info
1.0.0

* Helm charts user-supplied values

* Kubernetes version information:

* Kubernetes cluster kind:

**Additional context**

**Comment by adejanovski** [comment]
Starting the review.
