### ISSUE TITLE
Recover from corrupt SSTableException that can prevent Cassandra startup

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#681]
**Is your feature request related to a problem? Please describe.**
While I was working on some automated tests for medusa-operator, I found that one of my Cassandra instances failed to start. It was due to a CorruptSSTableException:

```
Exception (org.apache.cassandra.io.sstable.CorruptSSTableException) encountered during startup: Corrupted: /var/lib/cassandra/data/system/size_estimates-618f817b005f3678b8a453f3930b8e86/md-1-big-Data.db
org.apache.cassandra.io.sstable.CorruptSSTableException: Corrupted: /var/lib/cassandra/data/system/size_estimates-618f817b005f3678b8a453f3930b8e86/md-1-big-Data.db
	at org.apache.cassandra.io.sstable.format.big.BigTableScanner$KeyScanningIterator$1.initializeIterator(BigTableScanner.java:397)
	at org.apache.cassandra.db.rows.LazilyInitializedUnfilteredRowIterator.maybeInit(LazilyInitializedUnfilteredRowIterator.java:48)
	at org.apache.cassandra.db.rows.LazilyInitializedUnfilteredRowIterator.metadata(LazilyInitializedUnfilteredRowIterator.java:58)
	at org.apache.cassandra.db.transform.RTBoundValidator.applyToPartition(RTBoundValidator.java:60)
	at org.apache.cassandra.db.transform.RTBoundValidator.applyToPartition(RTBoundValidator.java:34)
	at org.apache.cassandra.db.transform.BasePartitions.hasNext(BasePartitions.java:96)
	at org.apache.cassandra.utils.MergeIterator$Candidate.advance(MergeIterator.java:374)
	at org.apache.cassandra.utils.MergeIterator$ManyToOne.advance(MergeIterator.java:186)
	at org.apache.cassandra.utils.MergeIterator$ManyToOne.computeNext(MergeIterator.java:155)
	at org.apache.cassandra.utils.AbstractIterator.hasNext(AbstractIterator.java:47)
	at org.apache.cassandra.db.partitions.UnfilteredPartitionIterators$4.hasNext(UnfilteredPartitionIterators.java:233)
	at org.apache.cassandra.db.transform.BasePartitions.hasNext(BasePartitions.java:92)
	at org.apache.cassandra.cql3.statements.SelectStatement.process(SelectStatement.java:786)
	at org.apache.cassandra.cql3.statements.SelectStatement.processResults(SelectStatement.java:438)
	at org.apache.cassandra.cql3.statements.SelectStatement.executeInternal(SelectStatement.java:460)
	at org.apache.cassandra.cql3.statements.SelectStatement.executeInternal(SelectStatement.java:444)
	at org.apache.cassandra.cql3.statements.SelectStatement.executeInternal(SelectStatement.java:117)
	at org.apache.cassandra.cql3.QueryProcessor.executeInternal(QueryProcessor.java:315)
	at org.apache.cassandra.db.SystemKeyspace.getTablesWithSizeEstimates(SystemKeyspace.java:1340)
	at org.apache.cassandra.service.StorageService.cleanupSizeEstimates(StorageService.java:3396)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:341)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:628)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:768)
Caused by: org.apache.cassandra.io.sstable.CorruptSSTableException: Corrupted: /var/lib/cassandra/data/system/size_estimates-618f817b005f3678b8a453f3930b8e86/md-1-big-Data.db
	at org.apache.cassandra.db.columniterator.AbstractSSTableIterator.<init>(AbstractSSTableIterator.java:143)
	at org.apache.cassandra.db.columniterator.SSTableIterator.<init>(SSTableIterator.java:49)
	at org.apache.cassandra.io.sstable.format.big.BigTableReader.iterator(BigTableReader.java:72)
	at org.apache.cassandra.io.sstable.format.big.BigTableScanner$KeyScanningIterator$1.initializeIterator(BigTableScanner.java:392)
	... 22 more
Caused by: java.io.EOFException: EOF after 1420 bytes out of 14391
	at org.apache.cassandra.io.util.DataInputPlus.skipBytesFully(DataInputPlus.java:58)
	at org.apache.cassandra.utils.ByteBufferUtil.skipShortLength(ByteBufferUtil.java:393)
	at org.apache.cassandra.db.columniterator.AbstractSSTableIterator.<init>(AbstractSSTableIterator.java:107)
	... 25 more
```
Because of #680 it was hard to determine that this was the problem. I had to start Cassandra in the foreground in the container to see the error.

**Describe the solution you'd like**
I would like cass-operator to provide a way to deal with corrupt SSTables. First, there needs to be a mechanism to identify the situation. Then I would like cass-operator to offer a solution for remediation. This might involve deleting the SSTable files, restarting Cassandra, and then running a repair.

I briefly discussed the problem I ran into with @adejanovski. He said that if the corrupt SSTable is from system.local then it might be best to replace the C* node. In this particular case with the table in question being size_estimates, it is of less concern and would not need to replace the node. (@adejanovski correct me if I am wrong).

**Comment by adejanovski** [comment]
> He said that if the corrupt SSTable is from system.local then it might be best to replace the C* node. In this particular case with the table in question being size_estimates, it is of less concern and would not need to replace the node.

I confirm both. Corrupt `system.local` can have an impact on the topology (possible data loss) while `size_estimates` is mostly helpful when using Spark to read from Cassandra to optimize the splits (but Spark will work even if the table is empty).
