### ISSUE TITLE
Token allocations are random when using 4.0 and lead to collisions

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra#732]
## Bug Report

**Describe the bug**
When collocating Cassandra pods on the same worker node using Cassandra 4.0, some nodes will fail to start due to tokens collisions:

```
INFO  [main] 2021-05-06 09:09:44,192 Gossiper.java:2110 - No gossip backlog; proceeding
INFO  [main] 2021-05-06 09:09:44,193 StorageService.java:1599 - JOINING: schema complete, ready to bootstrap
INFO  [main] 2021-05-06 09:09:44,193 StorageService.java:1599 - JOINING: waiting for pending range calculation
INFO  [main] 2021-05-06 09:09:44,193 StorageService.java:1599 - JOINING: calculation complete, ready to bootstrap
INFO  [main] 2021-05-06 09:09:44,197 StorageService.java:1599 - JOINING: getting bootstrap token
INFO  [main] 2021-05-06 09:09:44,198 BootStrapper.java:250 - Generated random tokens. tokens are [4916404158927833750, -1389173121663489945, 5083198339702642473, -4169687567737103308, -3820396588987121254, -930632370836328278, -7651905638036910085, -7132548803968952319, 6570178476170400202, 732244319226977375, -5562429418534086174, -6429970682779439091, -3132119538246048788, -8439012771966836414, -4842558979028939132, 6174033040364023532]
INFO  [main] 2021-05-06 09:09:44,204 ColumnFamilyStore.java:870 - Enqueuing flush of local: 2.846KiB (0%) on-heap, 0.000KiB (0%) off-heap
INFO  [PerDiskMemtableFlushWriter_0:2] 2021-05-06 09:09:44,213 Memtable.java:452 - Writing Memtable-local@1003054531(0.627KiB serialized bytes, 2 ops, 0%/0% of on/off-heap limit), flushed range = (null, null]
INFO  [PerDiskMemtableFlushWriter_0:2] 2021-05-06 09:09:44,214 Memtable.java:481 - Completed flushing /var/lib/cassandra/data/system/local-7ad54392bcdd35a684174e047860b377/na-41-big-Data.db (0.388KiB) for commitlog position CommitLogPosition(segmentId=1620292171353, position=40787)
INFO  [MemtableFlushWriter:2] 2021-05-06 09:09:44,232 LogTransaction.java:240 - Unfinished transaction log, deleting /var/lib/cassandra/data/system/local-7ad54392bcdd35a684174e047860b377/na_txn_flush_cc396ae0-ae4a-11eb-9534-c5d576268691.log
INFO  [main] 2021-05-06 09:09:44,236 StorageService.java:1599 - JOINING: sleeping 30000 ms for pending range setup
INFO  [main] 2021-05-06 09:10:14,236 StorageService.java:1599 - JOINING: Starting to bootstrap...
ERROR [main] 2021-05-06 09:10:14,251 CassandraDaemon.java:822 - Exception encountered during startup
java.lang.IllegalStateException: Multiple strict sources found for Full(/172.31.11.214:7000,(9096486175408947141,-9149794428708036724]), sources: [Full(/172.31.41.163:7000,(9096486175408947141,-9149794428708036724]), Full(/172.31.25.109:7000,(9096486175408947141,-9149794428708036724])]
	at org.apache.cassandra.dht.RangeStreamer.calculateRangesToFetchWithPreferredEndpoints(RangeStreamer.java:517)
	at org.apache.cassandra.dht.RangeStreamer.calculateRangesToFetchWithPreferredEndpoints(RangeStreamer.java:383)
	at org.apache.cassandra.dht.RangeStreamer.addRanges(RangeStreamer.java:320)
	at org.apache.cassandra.dht.BootStrapper.bootstrap(BootStrapper.java:81)
	at org.apache.cassandra.service.StorageService.startBootstrap(StorageService.java:1765)
	at org.apache.cassandra.service.StorageService.bootstrap(StorageService.java:1742)
	at org.apache.cassandra.service.StorageService.joinTokenRing(StorageService.java:1033)
	at org.apache.cassandra.service.StorageService.joinTokenRing(StorageService.java:994)
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:793)
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:723)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:400)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:676)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:800)
INFO  [StorageServiceShutdownHook] 2021-05-06 09:10:14,259 HintsService.java:220 - Paused hints dispatch
WARN  [StorageServiceShutdownHook] 2021-05-06 09:10:14,259 Gossiper.java:1912 - No local state, state is in silent shutdown, or node hasn't joined, not announcing shutdown
```

Looking at the `cassandra.yaml` file in the containers, I can see that the `allocate_tokens_for_replication_factor` is missing, which explains why `Generated random tokens` shows up in the logs.
While I don't get how random tokens could end up with collisions, generating random tokens with 16 vnodes per node will lead to imbalances that are no fit for production use.

**Expected behavior**
4.0 clusters should use the new token allocation algorithm by default and nodes should be able to bootstrap without token collisions.

**Environment (please complete the following information):**

* Helm charts version info

1.1.0

**Comment by jsanda** [comment]
I will go ahead and take this. I spent time with the cass-config-builder project yesterday to see what is involved in terms of building/testing images. I think I have a decent handle on it.
