### ISSUE TITLE
Document backing up to Digital Ocean Spaces with Medusa & K8ssandra

### ISSUE THREAD

**Issue by bradfordcp** [k8ssandra/k8ssandra#869]
As part of writing the installation docs for DOKS I kicked the tires on backing up to DO Spaces with Medusa. Configuration was pretty straightforward I modified the instructions for Minio and didn't have any issues. We should look at adding instructions under the backup and restore sections of the docs.

**Comment by bradfordcp** [comment]
See:
* https://github.com/bradfordcp/k8ssandra/blob/docs/install-do/docs/content/en/install/doks/_index.md#spaces 
* https://github.com/bradfordcp/k8ssandra/blob/docs/install-do/docs/content/en/install/doks/doks.values.yaml#L50-L58 and

**Comment by royrijkers** [comment]
After following the instruction I had the following error log from Medusa:

`Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/cassandra/medusa/service/grpc/server.py", line 158, in <module>
    medusa_pb2_grpc.add_MedusaServicer_to_server(MedusaService(config), server)
  File "/home/cassandra/medusa/service/grpc/server.py", line 44, in __init__
    self.storage = Storage(config=self.config.storage)
  File "/home/cassandra/medusa/storage/__init__.py", line 72, in __init__
    self.storage_driver = self._connect_storage()
  File "/home/cassandra/medusa/storage/__init__.py", line 88, in _connect_storage
    s3_storage = S3BaseStorage(self._config)
  File "/home/cassandra/medusa/storage/abstract_storage.py", line 39, in __init__
    self.driver = self.connect_storage()
  File "/home/cassandra/medusa/storage/s3_base_storage.py", line 58, in connect_storage
    aws_config.read_file(aws_file)
  File "/usr/lib/python3.6/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/usr/lib/python3.6/configparser.py", line 1080, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/etc/medusa-secrets/medusa_s3_credentials', line: 1
'apiVersion: v1\n'`

**Comment by bradfordcp** [comment]
That's my fault the `kubectl` command assumes that the file it is reading _is_ the aws config ini. Instead it is a Kubernetes YAML with the appropriate content (ie you should use `kubectl apply -f spaces.secret.yaml`.
